-- GENERATED by scripts/gen-schema-migrations.mjs.
-- Extensions + the uuidv7() default function every schema group's tables need to exist
-- BEFORE any CREATE TABLE runs. Applied on both connections db:migrate knows about.

-- @target: main

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE OR REPLACE FUNCTION uuidv7() RETURNS uuid AS $$
  -- Build a v7 UUID: unix_ts_ms (48 bits) | ver (4) | rand_a (12) | var (2) | rand_b (62)
  SELECT encode(
    set_bit(
      set_bit(
        overlay(
          uuid_send(gen_random_uuid())
          PLACING substring(int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3)
          FROM 1 FOR 6
        ),
        52, 1
      ),
      53, 1
    ),
    'hex'
  )::uuid;
$$ LANGUAGE sql VOLATILE;;

-- @target: formula

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE OR REPLACE FUNCTION uuidv7() RETURNS uuid AS $$
  -- Build a v7 UUID: unix_ts_ms (48 bits) | ver (4) | rand_a (12) | var (2) | rand_b (62)
  SELECT encode(
    set_bit(
      set_bit(
        overlay(
          uuid_send(gen_random_uuid())
          PLACING substring(int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3)
          FROM 1 FOR 6
        ),
        52, 1
      ),
      53, 1
    ),
    'hex'
  )::uuid;
$$ LANGUAGE sql VOLATILE;;
