-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @core/data-iam, @ra/data-org.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "iam";

CREATE TABLE IF NOT EXISTS "iam"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "iam"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "iam"."consents" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"user_id" uuid NOT NULL,
	"type" text NOT NULL,
	"version" text NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone
);

ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "user_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "version" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "granted_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."consents" ADD COLUMN IF NOT EXISTS "revoked_at" timestamp with time zone;
CREATE TABLE IF NOT EXISTS "iam"."credentials" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"password_hash" text NOT NULL,
	"password_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"password_history" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "iam"."credentials" ADD COLUMN IF NOT EXISTS "password_hash" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."credentials" ADD COLUMN IF NOT EXISTS "password_changed_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."credentials" ADD COLUMN IF NOT EXISTS "password_history" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "iam"."credentials" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."credentials" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "iam"."devices" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"user_id" uuid NOT NULL,
	"fingerprint" text,
	"platform" text,
	"last_seen_at" timestamp with time zone
);

ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "user_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "fingerprint" text;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "platform" text;
ALTER TABLE "iam"."devices" ADD COLUMN IF NOT EXISTS "last_seen_at" timestamp with time zone;
CREATE TABLE IF NOT EXISTS "iam"."org_members" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"org_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"org_unit_id" uuid,
	"role" text DEFAULT 'member' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL
);

ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "org_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "user_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "org_unit_id" uuid;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "role" text DEFAULT 'member' NOT NULL;
ALTER TABLE "iam"."org_members" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active' NOT NULL;
CREATE TABLE IF NOT EXISTS "iam"."org_units" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"org_id" uuid NOT NULL,
	"parent_id" uuid,
	"type" text NOT NULL,
	"name" text NOT NULL
);

ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "org_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "parent_id" uuid;
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."org_units" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "iam"."organizations" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"type" text NOT NULL,
	"name" text NOT NULL,
	"rera_no" text,
	"gstin" text,
	"status" text DEFAULT 'active' NOT NULL
);

ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "rera_no" text;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "gstin" text;
ALTER TABLE "iam"."organizations" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'active' NOT NULL;
CREATE TABLE IF NOT EXISTS "iam"."otps" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"user_id" uuid,
	"target" text NOT NULL,
	"channel" text NOT NULL,
	"code_hash" text NOT NULL,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone NOT NULL
);

ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "user_id" uuid;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "target" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "channel" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "code_hash" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "attempts" smallint DEFAULT 0 NOT NULL;
ALTER TABLE "iam"."otps" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "iam"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "iam"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "iam"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "iam"."partners" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"org_id" uuid NOT NULL,
	"category" text NOT NULL,
	"terms" jsonb
);

ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "org_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "category" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."partners" ADD COLUMN IF NOT EXISTS "terms" jsonb;
CREATE TABLE IF NOT EXISTS "iam"."permissions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"key" text NOT NULL,
	"description" text
);

ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."permissions" ADD COLUMN IF NOT EXISTS "description" text;
CREATE TABLE IF NOT EXISTS "iam"."role_permissions" (
	"role_id" uuid NOT NULL,
	"permission_id" uuid NOT NULL,
	CONSTRAINT "role_permissions_role_id_permission_id_pk" PRIMARY KEY("role_id","permission_id")
);

ALTER TABLE "iam"."role_permissions" ADD COLUMN IF NOT EXISTS "role_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."role_permissions" ADD COLUMN IF NOT EXISTS "permission_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "iam"."roles" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"scope" text DEFAULT 'platform' NOT NULL
);

ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."roles" ADD COLUMN IF NOT EXISTS "scope" text DEFAULT 'platform' NOT NULL;
CREATE TABLE IF NOT EXISTS "iam"."sessions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"user_id" uuid NOT NULL,
	"device_id" uuid,
	"refresh_token_hash" text NOT NULL,
	"portal_audience" text,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone
);

ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "user_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "device_id" uuid;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "refresh_token_hash" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "portal_audience" text;
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."sessions" ADD COLUMN IF NOT EXISTS "revoked_at" timestamp with time zone;
CREATE TABLE IF NOT EXISTS "iam"."user_roles" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"user_id" uuid NOT NULL,
	"role_id" uuid NOT NULL,
	"org_id" uuid
);

ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "user_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "role_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."user_roles" ADD COLUMN IF NOT EXISTS "org_id" uuid;
CREATE TABLE IF NOT EXISTS "iam"."users" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"mobile" text,
	"email" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"full_name" text,
	"deleted_at" timestamp with time zone
);

ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "mobile" text;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "email" text;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'pending' NOT NULL;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "full_name" text;
ALTER TABLE "iam"."users" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;
CREATE TABLE IF NOT EXISTS "iam"."approval_matrix" (
	"approval_matrix_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"policy_type" varchar(50) NOT NULL,
	"threshold_amount" numeric(18, 4),
	"is_enabled" boolean,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "organization_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "policy_type" varchar(50);  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "threshold_amount" numeric(18, 4);
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "is_enabled" boolean;
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."approval_matrix" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."assertion_jti" (
	"jti" varchar(255) PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "iam"."assertion_jti" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."assertion_jti" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "iam"."business_unit_master" (
	"business_unit_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid,
	"parent_business_unit_id" uuid,
	"business_unit_code" varchar(50),
	"business_unit_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "parent_business_unit_id" uuid;
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "business_unit_code" varchar(50);
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "business_unit_name" varchar(200);
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."business_unit_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."location_authority_master" (
	"location_authority_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid,
	"authority_user_id" uuid,
	"authority_role_id" uuid,
	"authority_type" varchar(50),
	"effective_from_dt" timestamp with time zone,
	"effective_to_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "authority_user_id" uuid;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "authority_role_id" uuid;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "authority_type" varchar(50);
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "effective_from_dt" timestamp with time zone;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "effective_to_dt" timestamp with time zone;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."location_authority_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."org_group_master" (
	"org_group_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"org_group_code" varchar(50),
	"org_group_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "org_group_code" varchar(50);
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "org_group_name" varchar(200);
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."org_group_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."org_master" (
	"organization_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"org_group_id" uuid,
	"org_type_id" uuid,
	"organization_code" varchar(50),
	"organization_name" varchar(200),
	"registration_country_id" uuid,
	"base_currency_id" uuid,
	"default_timezone_id" uuid,
	"default_language_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "org_group_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "org_type_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "organization_code" varchar(50);
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "organization_name" varchar(200);
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "registration_country_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "base_currency_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "default_timezone_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "default_language_id" uuid;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."org_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."org_relationship" (
	"org_relationship_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid,
	"related_organization_id" uuid,
	"relationship_type" varchar(30),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "related_organization_id" uuid;
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "relationship_type" varchar(30);
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."org_relationship" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."org_type_master" (
	"org_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"org_type_code" varchar(50),
	"org_type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "org_type_code" varchar(50);
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "org_type_name" varchar(200);
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."org_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."permission_master" (
	"permission_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"permission_code" varchar(50),
	"permission_name" varchar(200),
	"module_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "permission_code" varchar(50);
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "permission_name" varchar(200);
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "module_name" varchar(200);
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."permission_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."role_master" (
	"role_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"role_code" varchar(50),
	"role_name" varchar(200),
	"description" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "role_code" varchar(50);
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "role_name" varchar(200);
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."role_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."role_permission_mapping" (
	"role_permission_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"role_id" uuid,
	"permission_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "role_id" uuid;
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "permission_id" uuid;
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."role_permission_mapping" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."user_master" (
	"user_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid,
	"employee_code" varchar(50),
	"user_name" varchar(200),
	"email" varchar(150),
	"mobile_number" varchar(20),
	"password_hash" varchar(255),
	"is_active" boolean,
	"alembic_subject" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "employee_code" varchar(50);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "user_name" varchar(200);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "email" varchar(150);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "mobile_number" varchar(20);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "password_hash" varchar(255);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "is_active" boolean;
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "alembic_subject" varchar(255);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."user_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."user_role_mapping" (
	"user_role_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"user_id" uuid,
	"role_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "user_id" uuid;
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "role_id" uuid;
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."user_role_mapping" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "iam"."vault_role_grant_request" (
	"vault_role_grant_request_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"user_id" uuid,
	"role_id" uuid,
	"grant_status" varchar(30) DEFAULT 'PENDING' NOT NULL,
	"expires_dt" timestamp with time zone NOT NULL,
	"decided_by" uuid,
	"decided_dt" timestamp with time zone,
	"decision_reason" text,
	"user_role_mapping_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "user_id" uuid;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "role_id" uuid;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "grant_status" varchar(30) DEFAULT 'PENDING' NOT NULL;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "expires_dt" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "decided_by" uuid;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "decided_dt" timestamp with time zone;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "decision_reason" text;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "user_role_mapping_id" uuid;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "iam"."vault_role_grant_request" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "iam"."consents" ADD CONSTRAINT "consents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."credentials" ADD CONSTRAINT "credentials_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."devices" ADD CONSTRAINT "devices_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_members" ADD CONSTRAINT "org_members_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "iam"."organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_members" ADD CONSTRAINT "org_members_org_unit_id_org_units_id_fk" FOREIGN KEY ("org_unit_id") REFERENCES "iam"."org_units"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_units" ADD CONSTRAINT "org_units_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "iam"."organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."partners" ADD CONSTRAINT "partners_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "iam"."organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."role_permissions" ADD CONSTRAINT "role_permissions_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."role_permissions" ADD CONSTRAINT "role_permissions_permission_id_permissions_id_fk" FOREIGN KEY ("permission_id") REFERENCES "iam"."permissions"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."sessions" ADD CONSTRAINT "sessions_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "iam"."devices"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."user_roles" ADD CONSTRAINT "user_roles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."user_roles" ADD CONSTRAINT "user_roles_role_id_roles_id_fk" FOREIGN KEY ("role_id") REFERENCES "iam"."roles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."approval_matrix" ADD CONSTRAINT "approval_matrix_organization_id_org_master_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "iam"."org_master"("organization_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."business_unit_master" ADD CONSTRAINT "business_unit_master_organization_id_org_master_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "iam"."org_master"("organization_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."location_authority_master" ADD CONSTRAINT "location_authority_master_authority_user_id_user_master_user_id_fk" FOREIGN KEY ("authority_user_id") REFERENCES "iam"."user_master"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."location_authority_master" ADD CONSTRAINT "location_authority_master_authority_role_id_role_master_role_id_fk" FOREIGN KEY ("authority_role_id") REFERENCES "iam"."role_master"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_master" ADD CONSTRAINT "org_master_org_group_id_org_group_master_org_group_id_fk" FOREIGN KEY ("org_group_id") REFERENCES "iam"."org_group_master"("org_group_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_master" ADD CONSTRAINT "org_master_org_type_id_org_type_master_org_type_id_fk" FOREIGN KEY ("org_type_id") REFERENCES "iam"."org_type_master"("org_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_relationship" ADD CONSTRAINT "org_relationship_organization_id_org_master_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "iam"."org_master"("organization_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."org_relationship" ADD CONSTRAINT "org_relationship_related_organization_id_org_master_organization_id_fk" FOREIGN KEY ("related_organization_id") REFERENCES "iam"."org_master"("organization_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."role_permission_mapping" ADD CONSTRAINT "role_permission_mapping_role_id_role_master_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "iam"."role_master"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."role_permission_mapping" ADD CONSTRAINT "role_permission_mapping_permission_id_permission_master_permission_id_fk" FOREIGN KEY ("permission_id") REFERENCES "iam"."permission_master"("permission_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."user_master" ADD CONSTRAINT "user_master_organization_id_org_master_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "iam"."org_master"("organization_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."user_role_mapping" ADD CONSTRAINT "user_role_mapping_user_id_user_master_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."user_master"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."user_role_mapping" ADD CONSTRAINT "user_role_mapping_role_id_role_master_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "iam"."role_master"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."vault_role_grant_request" ADD CONSTRAINT "vault_role_grant_request_user_id_user_master_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "iam"."user_master"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."vault_role_grant_request" ADD CONSTRAINT "vault_role_grant_request_role_id_role_master_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "iam"."role_master"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."vault_role_grant_request" ADD CONSTRAINT "vault_role_grant_request_decided_by_user_master_user_id_fk" FOREIGN KEY ("decided_by") REFERENCES "iam"."user_master"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "iam"."vault_role_grant_request" ADD CONSTRAINT "vault_role_grant_request_user_role_mapping_id_user_role_mapping_user_role_mapping_id_fk" FOREIGN KEY ("user_role_mapping_id") REFERENCES "iam"."user_role_mapping"("user_role_mapping_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "iam"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "iam"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "iam"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "iam"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "iam"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "consents_user_idx" ON "iam"."consents" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "consents_type_idx" ON "iam"."consents" USING btree ("type");
CREATE UNIQUE INDEX IF NOT EXISTS "consents_user_type_active_uq" ON "iam"."consents" USING btree ("user_id","type") WHERE "iam"."consents"."revoked_at" IS NULL;
CREATE INDEX IF NOT EXISTS "devices_user_idx" ON "iam"."devices" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "devices_fingerprint_idx" ON "iam"."devices" USING btree ("fingerprint");
CREATE INDEX IF NOT EXISTS "org_members_org_idx" ON "iam"."org_members" USING btree ("org_id");
CREATE INDEX IF NOT EXISTS "org_members_user_idx" ON "iam"."org_members" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "org_members_unit_idx" ON "iam"."org_members" USING btree ("org_unit_id");
CREATE UNIQUE INDEX IF NOT EXISTS "org_members_org_user_uq" ON "iam"."org_members" USING btree ("org_id","user_id");
CREATE INDEX IF NOT EXISTS "org_units_org_idx" ON "iam"."org_units" USING btree ("org_id");
CREATE INDEX IF NOT EXISTS "org_units_parent_idx" ON "iam"."org_units" USING btree ("parent_id");
CREATE INDEX IF NOT EXISTS "organizations_type_idx" ON "iam"."organizations" USING btree ("type");
CREATE INDEX IF NOT EXISTS "organizations_status_idx" ON "iam"."organizations" USING btree ("status");
CREATE INDEX IF NOT EXISTS "organizations_name_trgm_idx" ON "iam"."organizations" USING gin ("name" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "otps_target_idx" ON "iam"."otps" USING btree ("target");
CREATE INDEX IF NOT EXISTS "otps_user_idx" ON "iam"."otps" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "otps_expires_idx" ON "iam"."otps" USING btree ("expires_at");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "iam"."outbox" USING btree ("occurred_at","seq") WHERE "iam"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "iam"."outbox" USING btree ("aggregate_id");
CREATE UNIQUE INDEX IF NOT EXISTS "partners_org_uq" ON "iam"."partners" USING btree ("org_id");
CREATE INDEX IF NOT EXISTS "partners_category_idx" ON "iam"."partners" USING btree ("category");
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_key_uq" ON "iam"."permissions" USING btree ("key");
CREATE INDEX IF NOT EXISTS "role_permissions_permission_idx" ON "iam"."role_permissions" USING btree ("permission_id");
CREATE UNIQUE INDEX IF NOT EXISTS "roles_key_uq" ON "iam"."roles" USING btree ("key");
CREATE INDEX IF NOT EXISTS "roles_scope_idx" ON "iam"."roles" USING btree ("scope");
CREATE INDEX IF NOT EXISTS "sessions_user_idx" ON "iam"."sessions" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "sessions_device_idx" ON "iam"."sessions" USING btree ("device_id");
CREATE INDEX IF NOT EXISTS "sessions_expires_idx" ON "iam"."sessions" USING btree ("expires_at");
CREATE INDEX IF NOT EXISTS "sessions_active_idx" ON "iam"."sessions" USING btree ("user_id","expires_at") WHERE "iam"."sessions"."revoked_at" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "user_roles_user_role_org_uq" ON "iam"."user_roles" USING btree ("user_id","role_id",COALESCE("org_id", '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX IF NOT EXISTS "user_roles_user_idx" ON "iam"."user_roles" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "user_roles_role_idx" ON "iam"."user_roles" USING btree ("role_id");
CREATE INDEX IF NOT EXISTS "user_roles_org_idx" ON "iam"."user_roles" USING btree ("org_id");
CREATE UNIQUE INDEX IF NOT EXISTS "users_mobile_active_uq" ON "iam"."users" USING btree ("mobile") WHERE "iam"."users"."deleted_at" IS NULL AND "iam"."users"."mobile" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_active_uq" ON "iam"."users" USING btree ("email") WHERE "iam"."users"."deleted_at" IS NULL AND "iam"."users"."email" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "users_status_idx" ON "iam"."users" USING btree ("status");
CREATE INDEX IF NOT EXISTS "users_deleted_at_idx" ON "iam"."users" USING btree ("deleted_at") WHERE "iam"."users"."deleted_at" IS NULL;
CREATE INDEX IF NOT EXISTS "users_full_name_trgm_idx" ON "iam"."users" USING gin ("full_name" gin_trgm_ops);
CREATE UNIQUE INDEX IF NOT EXISTS "approval_matrix_org_policy_uq" ON "iam"."approval_matrix" USING btree ("organization_id","policy_type");
CREATE INDEX IF NOT EXISTS "approval_matrix_org_idx" ON "iam"."approval_matrix" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "business_unit_master_org_idx" ON "iam"."business_unit_master" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "business_unit_master_parent_idx" ON "iam"."business_unit_master" USING btree ("parent_business_unit_id");
CREATE INDEX IF NOT EXISTS "location_authority_master_location_idx" ON "iam"."location_authority_master" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "location_authority_master_user_idx" ON "iam"."location_authority_master" USING btree ("authority_user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "org_group_master_code_uq" ON "iam"."org_group_master" USING btree ("org_group_code");
CREATE UNIQUE INDEX IF NOT EXISTS "org_master_code_uq" ON "iam"."org_master" USING btree ("organization_code");
CREATE INDEX IF NOT EXISTS "org_master_group_idx" ON "iam"."org_master" USING btree ("org_group_id");
CREATE INDEX IF NOT EXISTS "org_relationship_org_idx" ON "iam"."org_relationship" USING btree ("organization_id");
CREATE UNIQUE INDEX IF NOT EXISTS "org_type_master_code_uq" ON "iam"."org_type_master" USING btree ("org_type_code");
CREATE UNIQUE INDEX IF NOT EXISTS "permission_master_code_uq" ON "iam"."permission_master" USING btree ("permission_code");
CREATE UNIQUE INDEX IF NOT EXISTS "role_master_code_uq" ON "iam"."role_master" USING btree ("role_code");
CREATE UNIQUE INDEX IF NOT EXISTS "role_permission_mapping_uq" ON "iam"."role_permission_mapping" USING btree ("role_id","permission_id");
CREATE INDEX IF NOT EXISTS "role_permission_mapping_role_idx" ON "iam"."role_permission_mapping" USING btree ("role_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_master_email_uq" ON "iam"."user_master" USING btree ("email");
CREATE INDEX IF NOT EXISTS "user_master_org_idx" ON "iam"."user_master" USING btree ("organization_id");
CREATE UNIQUE INDEX IF NOT EXISTS "user_master_alembic_subject_uq" ON "iam"."user_master" USING btree ("alembic_subject") WHERE "iam"."user_master"."alembic_subject" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "user_role_mapping_uq" ON "iam"."user_role_mapping" USING btree ("user_id","role_id");
CREATE INDEX IF NOT EXISTS "user_role_mapping_user_idx" ON "iam"."user_role_mapping" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "vault_role_grant_request_user_idx" ON "iam"."vault_role_grant_request" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "vault_role_grant_request_status_idx" ON "iam"."vault_role_grant_request" USING btree ("grant_status");
