-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @core/data-platform, @ra/data-reference.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "platform";

CREATE TABLE IF NOT EXISTS "platform"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "platform"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "platform"."checklist_template_versions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"template_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"sections" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"published_at" timestamp with time zone
);

ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "template_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "version" integer;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "sections" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "platform"."checklist_template_versions" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
CREATE TABLE IF NOT EXISTS "platform"."checklist_templates" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"applies_to" jsonb,
	"status" text DEFAULT 'draft' NOT NULL,
	"current_version" integer DEFAULT 0 NOT NULL
);

ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "applies_to" jsonb;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'draft' NOT NULL;
ALTER TABLE "platform"."checklist_templates" ADD COLUMN IF NOT EXISTS "current_version" integer DEFAULT 0 NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."config" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"scope" text NOT NULL,
	"key" text NOT NULL,
	"value" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."config" ADD COLUMN IF NOT EXISTS "scope" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."config" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."config" ADD COLUMN IF NOT EXISTS "value" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "platform"."config" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."config" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."content_blocks" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"slot" text NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"publish_at" timestamp with time zone,
	"expire_at" timestamp with time zone,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "slot" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "locale" text DEFAULT 'en' NOT NULL;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "payload" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'draft' NOT NULL;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "publish_at" timestamp with time zone;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "expire_at" timestamp with time zone;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."content_blocks" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."flag_audit" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"flag_id" uuid NOT NULL,
	"env" text NOT NULL,
	"old_state" text,
	"new_state" text NOT NULL,
	"reason" text NOT NULL,
	"actor_id" uuid,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "flag_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "env" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "old_state" text;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "new_state" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "reason" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "platform"."flag_audit" ADD COLUMN IF NOT EXISTS "at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."flag_states" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"flag_id" uuid NOT NULL,
	"env" text NOT NULL,
	"state" text NOT NULL,
	"targeting" jsonb
);

ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "flag_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "env" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "state" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flag_states" ADD COLUMN IF NOT EXISTS "targeting" jsonb;
CREATE TABLE IF NOT EXISTS "platform"."flags" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"key" text NOT NULL,
	"description" text,
	"kind" text DEFAULT 'boolean' NOT NULL,
	"is_critical" boolean DEFAULT false NOT NULL,
	"default_state" text DEFAULT 'off' NOT NULL
);

ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "created_by" uuid;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "updated_by" uuid;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "kind" text DEFAULT 'boolean' NOT NULL;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "is_critical" boolean DEFAULT false NOT NULL;
ALTER TABLE "platform"."flags" ADD COLUMN IF NOT EXISTS "default_state" text DEFAULT 'off' NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."geo_region_types" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"typical_parent" text
);

ALTER TABLE "platform"."geo_region_types" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."geo_region_types" ADD COLUMN IF NOT EXISTS "display_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "platform"."geo_region_types" ADD COLUMN IF NOT EXISTS "typical_parent" text;
CREATE TABLE IF NOT EXISTS "platform"."geo_regions" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_key" text NOT NULL,
	"parent_id" uuid,
	"name" text NOT NULL,
	"code" text,
	"centroid" geometry(Point,4326),
	"boundary" geometry(MultiPolygon,4326),
	"metadata" jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "type_key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "parent_id" uuid;
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "code" text;
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "centroid" geometry(Point,4326);
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "boundary" geometry(MultiPolygon,4326);
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."geo_regions" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."master_items" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_key" text NOT NULL,
	"key" text NOT NULL,
	"label" text NOT NULL,
	"parent_id" uuid,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"metadata" jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "type_key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "key" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "label" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "parent_id" uuid;
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "metadata" jsonb;
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."master_items" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."master_types" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"is_hierarchical" boolean DEFAULT false NOT NULL
);

ALTER TABLE "platform"."master_types" ADD COLUMN IF NOT EXISTS "name" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."master_types" ADD COLUMN IF NOT EXISTS "is_hierarchical" boolean DEFAULT false NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "platform"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "platform"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "platform"."themes" (
	"portal" text PRIMARY KEY NOT NULL,
	"tokens" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "platform"."themes" ADD COLUMN IF NOT EXISTS "tokens" jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE "platform"."themes" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "platform"."address_master" (
	"address_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"address_line1" text,
	"address_line2" text,
	"city" varchar(255),
	"state_name" varchar(200),
	"country_id" uuid,
	"pincode" varchar(50),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "address_line1" text;
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "address_line2" text;
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "city" varchar(255);
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "state_name" varchar(200);
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "country_id" uuid;
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "pincode" varchar(50);
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."address_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."brand_master" (
	"brand_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"brand_code" varchar(50),
	"brand_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "brand_code" varchar(50);
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "brand_name" varchar(200);
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."brand_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."contact_master" (
	"contact_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"contact_name" varchar(200),
	"email" varchar(150),
	"mobile_number" varchar(20),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "contact_name" varchar(200);
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "email" varchar(150);
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "mobile_number" varchar(20);
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."contact_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."country_master" (
	"country_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"country_code" varchar(50),
	"country_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "country_code" varchar(50);
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "country_name" varchar(200);
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."country_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."currency_master" (
	"currency_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"currency_code" varchar(50),
	"currency_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "currency_code" varchar(50);
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "currency_name" varchar(200);
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."currency_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."document_master" (
	"document_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"document_type_id" uuid,
	"file_name" varchar(200),
	"file_path" varchar(255),
	"uploaded_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "document_type_id" uuid;
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "file_name" varchar(200);
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "file_path" varchar(255);
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "uploaded_dt" timestamp with time zone;
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."document_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."document_type_master" (
	"document_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"document_type_code" varchar(50),
	"document_type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "document_type_code" varchar(50);
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "document_type_name" varchar(200);
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."document_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."geo_location_master" (
	"geo_location_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "latitude" numeric(10, 8);
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "longitude" numeric(11, 8);
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."geo_location_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."language_master" (
	"language_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"language_code" varchar(50),
	"language_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "language_code" varchar(50);
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "language_name" varchar(200);
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."language_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."timezone_master" (
	"timezone_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"timezone_code" varchar(50),
	"utc_offset" varchar(20),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "timezone_code" varchar(50);
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "utc_offset" varchar(20);
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."timezone_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."uom_conversion_master" (
	"uom_conversion_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"uom_type_id" uuid,
	"from_uom_id" uuid,
	"to_uom_id" uuid,
	"conversion_factor" numeric(18, 8) NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "uom_type_id" uuid;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "from_uom_id" uuid;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "to_uom_id" uuid;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "conversion_factor" numeric(18, 8);  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."uom_conversion_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."uom_master" (
	"uom_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"uom_code" varchar(50),
	"uom_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "uom_code" varchar(50);
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "uom_name" varchar(200);
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."uom_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "platform"."uom_type_master" (
	"uom_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"description" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "platform"."uom_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "platform"."checklist_template_versions" ADD CONSTRAINT "checklist_template_versions_template_id_checklist_templates_id_fk" FOREIGN KEY ("template_id") REFERENCES "platform"."checklist_templates"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."flag_audit" ADD CONSTRAINT "flag_audit_flag_id_flags_id_fk" FOREIGN KEY ("flag_id") REFERENCES "platform"."flags"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."flag_states" ADD CONSTRAINT "flag_states_flag_id_flags_id_fk" FOREIGN KEY ("flag_id") REFERENCES "platform"."flags"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."geo_regions" ADD CONSTRAINT "geo_regions_type_key_geo_region_types_key_fk" FOREIGN KEY ("type_key") REFERENCES "platform"."geo_region_types"("key") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."master_items" ADD CONSTRAINT "master_items_type_key_master_types_key_fk" FOREIGN KEY ("type_key") REFERENCES "platform"."master_types"("key") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."address_master" ADD CONSTRAINT "address_master_country_id_country_master_country_id_fk" FOREIGN KEY ("country_id") REFERENCES "platform"."country_master"("country_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."document_master" ADD CONSTRAINT "document_master_document_type_id_document_type_master_document_type_id_fk" FOREIGN KEY ("document_type_id") REFERENCES "platform"."document_type_master"("document_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."uom_conversion_master" ADD CONSTRAINT "uom_conversion_master_uom_type_id_uom_type_master_uom_type_id_fk" FOREIGN KEY ("uom_type_id") REFERENCES "platform"."uom_type_master"("uom_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."uom_conversion_master" ADD CONSTRAINT "uom_conversion_master_from_uom_id_uom_master_uom_id_fk" FOREIGN KEY ("from_uom_id") REFERENCES "platform"."uom_master"("uom_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "platform"."uom_conversion_master" ADD CONSTRAINT "uom_conversion_master_to_uom_id_uom_master_uom_id_fk" FOREIGN KEY ("to_uom_id") REFERENCES "platform"."uom_master"("uom_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "platform"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "platform"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "platform"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "platform"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "platform"."audit_events" USING btree ("chain_seq");
CREATE UNIQUE INDEX IF NOT EXISTS "checklist_template_versions_template_version_uq" ON "platform"."checklist_template_versions" USING btree ("template_id","version");
CREATE INDEX IF NOT EXISTS "checklist_template_versions_template_idx" ON "platform"."checklist_template_versions" USING btree ("template_id");
CREATE UNIQUE INDEX IF NOT EXISTS "checklist_templates_key_uq" ON "platform"."checklist_templates" USING btree ("key");
CREATE INDEX IF NOT EXISTS "checklist_templates_status_idx" ON "platform"."checklist_templates" USING btree ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "config_scope_key_uq" ON "platform"."config" USING btree ("scope","key");
CREATE INDEX IF NOT EXISTS "content_blocks_slot_locale_idx" ON "platform"."content_blocks" USING btree ("slot","locale","sort_order");
CREATE INDEX IF NOT EXISTS "content_blocks_status_idx" ON "platform"."content_blocks" USING btree ("status");
CREATE INDEX IF NOT EXISTS "flag_audit_flag_idx" ON "platform"."flag_audit" USING btree ("flag_id");
CREATE INDEX IF NOT EXISTS "flag_audit_env_idx" ON "platform"."flag_audit" USING btree ("env");
CREATE INDEX IF NOT EXISTS "flag_audit_at_idx" ON "platform"."flag_audit" USING btree ("at");
CREATE UNIQUE INDEX IF NOT EXISTS "flag_states_flag_env_uq" ON "platform"."flag_states" USING btree ("flag_id","env");
CREATE INDEX IF NOT EXISTS "flag_states_env_idx" ON "platform"."flag_states" USING btree ("env");
CREATE UNIQUE INDEX IF NOT EXISTS "flags_key_uq" ON "platform"."flags" USING btree ("key");
CREATE INDEX IF NOT EXISTS "geo_regions_type_idx" ON "platform"."geo_regions" USING btree ("type_key");
CREATE INDEX IF NOT EXISTS "geo_regions_parent_idx" ON "platform"."geo_regions" USING btree ("parent_id");
CREATE INDEX IF NOT EXISTS "geo_regions_code_idx" ON "platform"."geo_regions" USING btree ("code");
CREATE INDEX IF NOT EXISTS "geo_regions_active_idx" ON "platform"."geo_regions" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "geo_regions_name_trgm_idx" ON "platform"."geo_regions" USING gin ("name" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "geo_regions_centroid_gist" ON "platform"."geo_regions" USING gist ("centroid");
CREATE INDEX IF NOT EXISTS "geo_regions_boundary_gist" ON "platform"."geo_regions" USING gist ("boundary");
CREATE UNIQUE INDEX IF NOT EXISTS "master_items_type_key_uq" ON "platform"."master_items" USING btree ("type_key","key");
CREATE INDEX IF NOT EXISTS "master_items_type_idx" ON "platform"."master_items" USING btree ("type_key");
CREATE INDEX IF NOT EXISTS "master_items_parent_idx" ON "platform"."master_items" USING btree ("parent_id");
CREATE INDEX IF NOT EXISTS "master_items_active_idx" ON "platform"."master_items" USING btree ("is_active");
CREATE INDEX IF NOT EXISTS "master_items_label_trgm_idx" ON "platform"."master_items" USING gin ("label" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "platform"."outbox" USING btree ("occurred_at","seq") WHERE "platform"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "platform"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "address_master_country_idx" ON "platform"."address_master" USING btree ("country_id");
CREATE UNIQUE INDEX IF NOT EXISTS "brand_master_code_uq" ON "platform"."brand_master" USING btree ("brand_code");
CREATE UNIQUE INDEX IF NOT EXISTS "country_master_code_uq" ON "platform"."country_master" USING btree ("country_code");
CREATE UNIQUE INDEX IF NOT EXISTS "currency_master_code_uq" ON "platform"."currency_master" USING btree ("currency_code");
CREATE INDEX IF NOT EXISTS "document_master_type_idx" ON "platform"."document_master" USING btree ("document_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "document_type_master_code_uq" ON "platform"."document_type_master" USING btree ("document_type_code");
CREATE UNIQUE INDEX IF NOT EXISTS "language_master_code_uq" ON "platform"."language_master" USING btree ("language_code");
CREATE UNIQUE INDEX IF NOT EXISTS "timezone_master_code_uq" ON "platform"."timezone_master" USING btree ("timezone_code");
CREATE INDEX IF NOT EXISTS "uom_conversion_master_type_idx" ON "platform"."uom_conversion_master" USING btree ("uom_type_id");
CREATE INDEX IF NOT EXISTS "uom_conversion_master_from_idx" ON "platform"."uom_conversion_master" USING btree ("from_uom_id");
CREATE INDEX IF NOT EXISTS "uom_conversion_master_to_idx" ON "platform"."uom_conversion_master" USING btree ("to_uom_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uom_master_code_uq" ON "platform"."uom_master" USING btree ("uom_code");
CREATE UNIQUE INDEX IF NOT EXISTS "uom_type_master_code_uq" ON "platform"."uom_type_master" USING btree ("type_code");
