-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-location.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "location";

CREATE TABLE IF NOT EXISTS "location"."bin_master" (
	"bin_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"shelf_id" uuid,
	"bin_code" varchar(50),
	"bin_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "shelf_id" uuid;
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "bin_code" varchar(50);
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "bin_name" varchar(200);
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."bin_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."floor_master" (
	"floor_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"warehouse_id" uuid,
	"floor_code" varchar(50),
	"floor_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "warehouse_id" uuid;
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "floor_code" varchar(50);
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "floor_name" varchar(200);
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."floor_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."location_master" (
	"location_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid,
	"business_unit_id" uuid,
	"parent_location_id" uuid,
	"location_type_id" uuid,
	"location_code" varchar(50),
	"location_name" varchar(200),
	"address_id" uuid,
	"geo_location_id" uuid,
	"primary_contact_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "business_unit_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "parent_location_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "location_type_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "location_code" varchar(50);
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "location_name" varchar(200);
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "address_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "geo_location_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "primary_contact_id" uuid;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."location_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."location_type_master" (
	"location_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."location_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."rack_master" (
	"rack_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"zone_id" uuid,
	"rack_code" varchar(50),
	"rack_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "zone_id" uuid;
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "rack_code" varchar(50);
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "rack_name" varchar(200);
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."rack_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."shelf_master" (
	"shelf_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rack_id" uuid,
	"shelf_code" varchar(50),
	"shelf_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "rack_id" uuid;
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "shelf_code" varchar(50);
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "shelf_name" varchar(200);
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."shelf_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."storage_location_master" (
	"storage_location_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"warehouse_id" uuid,
	"floor_id" uuid,
	"zone_id" uuid,
	"rack_id" uuid,
	"shelf_id" uuid,
	"bin_id" uuid,
	"storage_location_code" varchar(50),
	"storage_location_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "warehouse_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "floor_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "zone_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "rack_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "shelf_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "bin_id" uuid;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "storage_location_code" varchar(50);
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "storage_location_name" varchar(200);
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."storage_location_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."storage_location_status_master" (
	"storage_location_status_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"status_code" varchar(50),
	"status_name" varchar(200),
	"description" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "status_code" varchar(50);
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "status_name" varchar(200);
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."storage_location_status_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."storage_location_type_master" (
	"storage_location_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."storage_location_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."warehouse_master" (
	"warehouse_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid,
	"warehouse_type_id" uuid,
	"warehouse_code" varchar(50),
	"warehouse_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "warehouse_type_id" uuid;
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "warehouse_code" varchar(50);
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "warehouse_name" varchar(200);
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."warehouse_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."warehouse_type_master" (
	"warehouse_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."warehouse_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."zone_master" (
	"zone_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"floor_id" uuid,
	"zone_type_id" uuid,
	"zone_code" varchar(50),
	"zone_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "floor_id" uuid;
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "zone_type_id" uuid;
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "zone_code" varchar(50);
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "zone_name" varchar(200);
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."zone_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "location"."zone_type_master" (
	"zone_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "location"."zone_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "location"."bin_master" ADD CONSTRAINT "bin_master_shelf_id_shelf_master_shelf_id_fk" FOREIGN KEY ("shelf_id") REFERENCES "location"."shelf_master"("shelf_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."floor_master" ADD CONSTRAINT "floor_master_warehouse_id_warehouse_master_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "location"."warehouse_master"("warehouse_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."location_master" ADD CONSTRAINT "location_master_location_type_id_location_type_master_location_type_id_fk" FOREIGN KEY ("location_type_id") REFERENCES "location"."location_type_master"("location_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."rack_master" ADD CONSTRAINT "rack_master_zone_id_zone_master_zone_id_fk" FOREIGN KEY ("zone_id") REFERENCES "location"."zone_master"("zone_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."shelf_master" ADD CONSTRAINT "shelf_master_rack_id_rack_master_rack_id_fk" FOREIGN KEY ("rack_id") REFERENCES "location"."rack_master"("rack_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_warehouse_id_warehouse_master_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "location"."warehouse_master"("warehouse_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_floor_id_floor_master_floor_id_fk" FOREIGN KEY ("floor_id") REFERENCES "location"."floor_master"("floor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_zone_id_zone_master_zone_id_fk" FOREIGN KEY ("zone_id") REFERENCES "location"."zone_master"("zone_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_rack_id_rack_master_rack_id_fk" FOREIGN KEY ("rack_id") REFERENCES "location"."rack_master"("rack_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_shelf_id_shelf_master_shelf_id_fk" FOREIGN KEY ("shelf_id") REFERENCES "location"."shelf_master"("shelf_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."storage_location_master" ADD CONSTRAINT "storage_location_master_bin_id_bin_master_bin_id_fk" FOREIGN KEY ("bin_id") REFERENCES "location"."bin_master"("bin_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."warehouse_master" ADD CONSTRAINT "warehouse_master_location_id_location_master_location_id_fk" FOREIGN KEY ("location_id") REFERENCES "location"."location_master"("location_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."warehouse_master" ADD CONSTRAINT "warehouse_master_warehouse_type_id_warehouse_type_master_warehouse_type_id_fk" FOREIGN KEY ("warehouse_type_id") REFERENCES "location"."warehouse_type_master"("warehouse_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."zone_master" ADD CONSTRAINT "zone_master_floor_id_floor_master_floor_id_fk" FOREIGN KEY ("floor_id") REFERENCES "location"."floor_master"("floor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "location"."zone_master" ADD CONSTRAINT "zone_master_zone_type_id_zone_type_master_zone_type_id_fk" FOREIGN KEY ("zone_type_id") REFERENCES "location"."zone_type_master"("zone_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "bin_master_code_uq" ON "location"."bin_master" USING btree ("bin_code");
CREATE INDEX IF NOT EXISTS "bin_master_shelf_idx" ON "location"."bin_master" USING btree ("shelf_id");
CREATE UNIQUE INDEX IF NOT EXISTS "floor_master_code_uq" ON "location"."floor_master" USING btree ("floor_code");
CREATE INDEX IF NOT EXISTS "floor_master_warehouse_idx" ON "location"."floor_master" USING btree ("warehouse_id");
CREATE UNIQUE INDEX IF NOT EXISTS "location_master_code_uq" ON "location"."location_master" USING btree ("location_code");
CREATE INDEX IF NOT EXISTS "location_master_type_idx" ON "location"."location_master" USING btree ("location_type_id");
CREATE INDEX IF NOT EXISTS "location_master_parent_idx" ON "location"."location_master" USING btree ("parent_location_id");
CREATE INDEX IF NOT EXISTS "location_master_org_idx" ON "location"."location_master" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "location_master_business_unit_idx" ON "location"."location_master" USING btree ("business_unit_id");
CREATE UNIQUE INDEX IF NOT EXISTS "location_type_master_code_uq" ON "location"."location_type_master" USING btree ("type_code");
CREATE UNIQUE INDEX IF NOT EXISTS "rack_master_code_uq" ON "location"."rack_master" USING btree ("rack_code");
CREATE INDEX IF NOT EXISTS "rack_master_zone_idx" ON "location"."rack_master" USING btree ("zone_id");
CREATE UNIQUE INDEX IF NOT EXISTS "shelf_master_code_uq" ON "location"."shelf_master" USING btree ("shelf_code");
CREATE INDEX IF NOT EXISTS "shelf_master_rack_idx" ON "location"."shelf_master" USING btree ("rack_id");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_location_master_code_uq" ON "location"."storage_location_master" USING btree ("storage_location_code");
CREATE INDEX IF NOT EXISTS "storage_location_master_warehouse_idx" ON "location"."storage_location_master" USING btree ("warehouse_id");
CREATE INDEX IF NOT EXISTS "storage_location_master_floor_idx" ON "location"."storage_location_master" USING btree ("floor_id");
CREATE INDEX IF NOT EXISTS "storage_location_master_zone_idx" ON "location"."storage_location_master" USING btree ("zone_id");
CREATE INDEX IF NOT EXISTS "storage_location_master_rack_idx" ON "location"."storage_location_master" USING btree ("rack_id");
CREATE INDEX IF NOT EXISTS "storage_location_master_shelf_idx" ON "location"."storage_location_master" USING btree ("shelf_id");
CREATE INDEX IF NOT EXISTS "storage_location_master_bin_idx" ON "location"."storage_location_master" USING btree ("bin_id");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_location_status_master_code_uq" ON "location"."storage_location_status_master" USING btree ("status_code");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_location_type_master_code_uq" ON "location"."storage_location_type_master" USING btree ("type_code");
CREATE UNIQUE INDEX IF NOT EXISTS "warehouse_master_code_uq" ON "location"."warehouse_master" USING btree ("warehouse_code");
CREATE INDEX IF NOT EXISTS "warehouse_master_location_idx" ON "location"."warehouse_master" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "warehouse_master_type_idx" ON "location"."warehouse_master" USING btree ("warehouse_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "warehouse_type_master_code_uq" ON "location"."warehouse_type_master" USING btree ("type_code");
CREATE UNIQUE INDEX IF NOT EXISTS "zone_master_code_uq" ON "location"."zone_master" USING btree ("zone_code");
CREATE INDEX IF NOT EXISTS "zone_master_floor_idx" ON "location"."zone_master" USING btree ("floor_id");
CREATE INDEX IF NOT EXISTS "zone_master_type_idx" ON "location"."zone_master" USING btree ("zone_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "zone_type_master_code_uq" ON "location"."zone_type_master" USING btree ("type_code");
