-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-masterdata.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "masterdata";

CREATE TABLE IF NOT EXISTS "masterdata"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "masterdata"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "masterdata"."material" (
	"material_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_group_id" uuid,
	"material_type_id" uuid,
	"material_category_id" uuid,
	"material_code" varchar(50),
	"material_name" varchar(200),
	"uom_id" uuid,
	"description" text,
	"scientific_name" text,
	"density" numeric(12, 4),
	"cas_number" text,
	"shelf_life_days" integer,
	"reorder_level" numeric(18, 4),
	"min_stock" numeric(18, 4),
	"max_stock" numeric(18, 4),
	"qc_required" boolean,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "material_group_id" uuid;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "material_type_id" uuid;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "material_category_id" uuid;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "material_code" varchar(50);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "material_name" varchar(200);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "scientific_name" text;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "density" numeric(12, 4);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "cas_number" text;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "shelf_life_days" integer;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "reorder_level" numeric(18, 4);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "min_stock" numeric(18, 4);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "max_stock" numeric(18, 4);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "qc_required" boolean;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_ageing" (
	"material_ageing_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_id" uuid,
	"inventory_batch_id" uuid,
	"storage_location_id" uuid,
	"quantity_on_hand" numeric(18, 4),
	"uom_id" uuid,
	"receipt_date" date,
	"snapshot_date" date,
	"ageing_days" integer,
	"ageing_bucket" varchar(50),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "storage_location_id" uuid;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "quantity_on_hand" numeric(18, 4);
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "receipt_date" date;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "snapshot_date" date;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "ageing_days" integer;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "ageing_bucket" varchar(50);
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_ageing" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_category_master" (
	"material_category_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_type_id" uuid,
	"category_code" varchar(50),
	"category_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "material_type_id" uuid;
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "category_code" varchar(50);
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "category_name" varchar(200);
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_category_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_group" (
	"material_group_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_subcategory_id" uuid,
	"group_code" varchar(50),
	"group_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "material_subcategory_id" uuid;
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "group_code" varchar(50);
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "group_name" varchar(200);
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_group" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_qc_specifications" (
	"material_qc_specification_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_id" uuid,
	"qc_parameter_id" uuid,
	"min_value" numeric(18, 4),
	"max_value" numeric(18, 4),
	"target_value" numeric(18, 4),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "qc_parameter_id" uuid;
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "min_value" numeric(18, 4);
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "max_value" numeric(18, 4);
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "target_value" numeric(18, 4);
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_qc_specifications" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_storage_rules" (
	"material_storage_rule_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_id" uuid,
	"storage_location_type_id" uuid,
	"min_temperature" varchar(255),
	"max_temperature" varchar(255),
	"storage_condition" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "storage_location_type_id" uuid;
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "min_temperature" varchar(255);
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "max_temperature" varchar(255);
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "storage_condition" varchar(255);
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_storage_rules" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_subcategory_master" (
	"material_subcategory_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_category_id" uuid,
	"sub_category_code" varchar(50),
	"sub_category_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "material_category_id" uuid;
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "sub_category_code" varchar(50);
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "sub_category_name" varchar(200);
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_subcategory_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."material_type_master" (
	"material_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."material_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "masterdata"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "masterdata"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "masterdata"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "masterdata"."rm_alias" (
	"rm_alias_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_id" uuid,
	"alias_name" varchar(200),
	"alias_type" varchar(30),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "alias_name" varchar(200);
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "alias_type" varchar(30);
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "masterdata"."rm_alias" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "masterdata"."material" ADD CONSTRAINT "material_material_group_id_material_group_material_group_id_fk" FOREIGN KEY ("material_group_id") REFERENCES "masterdata"."material_group"("material_group_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material" ADD CONSTRAINT "material_material_type_id_material_type_master_material_type_id_fk" FOREIGN KEY ("material_type_id") REFERENCES "masterdata"."material_type_master"("material_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material" ADD CONSTRAINT "material_material_category_id_material_category_master_material_category_id_fk" FOREIGN KEY ("material_category_id") REFERENCES "masterdata"."material_category_master"("material_category_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_ageing" ADD CONSTRAINT "material_ageing_material_id_material_material_id_fk" FOREIGN KEY ("material_id") REFERENCES "masterdata"."material"("material_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_category_master" ADD CONSTRAINT "material_category_master_material_type_id_material_type_master_material_type_id_fk" FOREIGN KEY ("material_type_id") REFERENCES "masterdata"."material_type_master"("material_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_group" ADD CONSTRAINT "material_group_material_subcategory_id_material_subcategory_master_material_subcategory_id_fk" FOREIGN KEY ("material_subcategory_id") REFERENCES "masterdata"."material_subcategory_master"("material_subcategory_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_qc_specifications" ADD CONSTRAINT "material_qc_specifications_material_id_material_material_id_fk" FOREIGN KEY ("material_id") REFERENCES "masterdata"."material"("material_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_storage_rules" ADD CONSTRAINT "material_storage_rules_material_id_material_material_id_fk" FOREIGN KEY ("material_id") REFERENCES "masterdata"."material"("material_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."material_subcategory_master" ADD CONSTRAINT "material_subcategory_master_material_category_id_material_category_master_material_category_id_fk" FOREIGN KEY ("material_category_id") REFERENCES "masterdata"."material_category_master"("material_category_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "masterdata"."rm_alias" ADD CONSTRAINT "rm_alias_material_id_material_material_id_fk" FOREIGN KEY ("material_id") REFERENCES "masterdata"."material"("material_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "masterdata"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "masterdata"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "masterdata"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "masterdata"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "masterdata"."audit_events" USING btree ("chain_seq");
CREATE UNIQUE INDEX IF NOT EXISTS "material_code_uq" ON "masterdata"."material" USING btree ("material_code");
CREATE INDEX IF NOT EXISTS "material_group_idx" ON "masterdata"."material" USING btree ("material_group_id");
CREATE INDEX IF NOT EXISTS "material_type_idx" ON "masterdata"."material" USING btree ("material_type_id");
CREATE INDEX IF NOT EXISTS "material_category_idx" ON "masterdata"."material" USING btree ("material_category_id");
CREATE INDEX IF NOT EXISTS "material_uom_idx" ON "masterdata"."material" USING btree ("uom_id");
CREATE INDEX IF NOT EXISTS "material_ageing_material_idx" ON "masterdata"."material_ageing" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "material_ageing_inventory_batch_idx" ON "masterdata"."material_ageing" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "material_ageing_storage_location_idx" ON "masterdata"."material_ageing" USING btree ("storage_location_id");
CREATE UNIQUE INDEX IF NOT EXISTS "material_category_master_code_uq" ON "masterdata"."material_category_master" USING btree ("category_code");
CREATE INDEX IF NOT EXISTS "material_category_master_type_idx" ON "masterdata"."material_category_master" USING btree ("material_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "material_group_code_uq" ON "masterdata"."material_group" USING btree ("group_code");
CREATE INDEX IF NOT EXISTS "material_group_subcategory_idx" ON "masterdata"."material_group" USING btree ("material_subcategory_id");
CREATE INDEX IF NOT EXISTS "material_qc_specifications_material_idx" ON "masterdata"."material_qc_specifications" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "material_qc_specifications_qc_parameter_idx" ON "masterdata"."material_qc_specifications" USING btree ("qc_parameter_id");
CREATE INDEX IF NOT EXISTS "material_storage_rules_material_idx" ON "masterdata"."material_storage_rules" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "material_storage_rules_storage_location_type_idx" ON "masterdata"."material_storage_rules" USING btree ("storage_location_type_id");
CREATE UNIQUE INDEX IF NOT EXISTS "material_subcategory_master_code_uq" ON "masterdata"."material_subcategory_master" USING btree ("sub_category_code");
CREATE INDEX IF NOT EXISTS "material_subcategory_master_category_idx" ON "masterdata"."material_subcategory_master" USING btree ("material_category_id");
CREATE UNIQUE INDEX IF NOT EXISTS "material_type_master_code_uq" ON "masterdata"."material_type_master" USING btree ("type_code");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "masterdata"."outbox" USING btree ("occurred_at","seq") WHERE "masterdata"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "masterdata"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "rm_alias_material_idx" ON "masterdata"."rm_alias" USING btree ("material_id");
