-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-procurement.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "procurement";

CREATE TABLE IF NOT EXISTS "procurement"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "procurement"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "procurement"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "procurement"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "procurement"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "procurement"."po_approval_order" (
	"po_approval_order_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"purchase_order_id" uuid,
	"approver_user_id" uuid,
	"approval_level" integer,
	"approval_status" varchar(30),
	"approved_dt" timestamp with time zone,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "approver_user_id" uuid;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "approval_level" integer;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "approval_status" varchar(30);
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."po_approval_order" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."purchase_order" (
	"purchase_order_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"po_number" varchar(50),
	"vendor_id" uuid,
	"quotation_id" uuid,
	"purchase_request_id" uuid,
	"order_date" date,
	"delivery_location_id" uuid,
	"currency_id" uuid,
	"total_amount" numeric(18, 4),
	"replacement_of_po_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "po_number" varchar(50);
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "quotation_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "purchase_request_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "order_date" date;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "delivery_location_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "currency_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "total_amount" numeric(18, 4);
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "replacement_of_po_id" uuid;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."purchase_order" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."purchase_order_items" (
	"purchase_order_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"purchase_order_id" uuid,
	"material_id" uuid,
	"ordered_qty" numeric(18, 4),
	"uom_id" uuid,
	"rate" numeric(18, 4),
	"amount" numeric(18, 4),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "ordered_qty" numeric(18, 4);
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "rate" numeric(18, 4);
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "amount" numeric(18, 4);
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."purchase_order_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."purchase_request" (
	"purchase_request_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"pr_number" varchar(50),
	"stock_requirement_id" uuid,
	"request_location_id" uuid,
	"delivery_location_id" uuid,
	"priority" varchar(255),
	"expected_delivery_date" date,
	"approved_by" uuid,
	"approved_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "pr_number" varchar(50);
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "stock_requirement_id" uuid;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "request_location_id" uuid;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "delivery_location_id" uuid;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "priority" varchar(255);
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "expected_delivery_date" date;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "approved_by" uuid;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."purchase_request" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."purchase_request_approval" (
	"purchase_request_approval_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"purchase_request_id" uuid,
	"approver_user_id" uuid,
	"approval_level" integer,
	"approval_status" varchar(30),
	"approved_dt" timestamp with time zone,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "purchase_request_id" uuid;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "approver_user_id" uuid;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "approval_level" integer;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "approval_status" varchar(30);
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."purchase_request_approval" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."purchase_request_items" (
	"purchase_request_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"purchase_request_id" uuid,
	"material_id" uuid,
	"required_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "purchase_request_id" uuid;
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."purchase_request_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."quotation_items" (
	"quotation_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"quotation_id" uuid,
	"material_id" uuid,
	"quoted_qty" numeric(18, 4),
	"uom_id" uuid,
	"quoted_rate" numeric(18, 4),
	"currency_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "quotation_id" uuid;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "quoted_qty" numeric(18, 4);
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "quoted_rate" numeric(18, 4);
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "currency_id" uuid;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."quotation_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."quotations" (
	"quotation_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rfq_id" uuid,
	"vendor_id" uuid,
	"quotation_number" varchar(50),
	"quotation_date" date,
	"valid_until_date" date,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "rfq_id" uuid;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "quotation_number" varchar(50);
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "quotation_date" date;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "valid_until_date" date;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."quotations" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."rfq_items" (
	"rfq_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rfq_id" uuid,
	"material_id" uuid,
	"required_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "rfq_id" uuid;
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."rfq_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."rfq_master" (
	"rfq_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rfq_number" varchar(50),
	"purchase_request_id" uuid,
	"rfq_date" date,
	"submission_deadline" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "rfq_number" varchar(50);
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "purchase_request_id" uuid;
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "rfq_date" date;
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "submission_deadline" varchar(255);
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."rfq_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."rfq_vendor_mappings" (
	"rfq_vendor_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rfq_id" uuid,
	"vendor_id" uuid,
	"is_selected_vendor" boolean,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "rfq_id" uuid;
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "is_selected_vendor" boolean;
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."rfq_vendor_mappings" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."stock_req_items" (
	"stock_req_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"stock_requirement_id" uuid,
	"material_id" uuid,
	"required_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "stock_requirement_id" uuid;
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."stock_req_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."stock_requirement" (
	"stock_requirement_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid,
	"material_id" uuid,
	"required_qty" numeric(18, 4),
	"uom_id" uuid,
	"required_by_date" date,
	"requirement_source" varchar(255),
	"priority" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "required_by_date" date;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "requirement_source" varchar(255);
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "priority" varchar(255);
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."stock_requirement" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_contact" (
	"vendor_contact_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"vendor_id" uuid,
	"contact_name" varchar(200),
	"designation" varchar(255),
	"email" varchar(150),
	"mobile_number" varchar(20),
	"is_primary" boolean,
	"contact_type" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "contact_name" varchar(200);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "designation" varchar(255);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "email" varchar(150);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "mobile_number" varchar(20);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "is_primary" boolean;
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "contact_type" text;
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_contact" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_credit_note" (
	"vendor_credit_note_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"vendor_id" uuid,
	"grn_id" uuid,
	"vendor_credit_reason_id" uuid,
	"credit_note_number" varchar(50),
	"credit_note_date" date,
	"amount" numeric(18, 4),
	"currency_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "grn_id" uuid;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "vendor_credit_reason_id" uuid;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "credit_note_number" varchar(50);
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "credit_note_date" date;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "amount" numeric(18, 4);
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "currency_id" uuid;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_credit_note" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_credit_notes_allocation" (
	"vendor_credit_notes_allocation_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"vendor_credit_note_id" uuid,
	"purchase_order_id" uuid,
	"allocated_amount" numeric(18, 4),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "vendor_credit_note_id" uuid;
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "allocated_amount" numeric(18, 4);
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_credit_reason_master" (
	"vendor_credit_reason_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"reason_code" varchar(50),
	"reason_description" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "reason_code" varchar(50);
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "reason_description" text;
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_credit_reason_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_details" (
	"vendor_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid,
	"vendor_code" varchar(50),
	"vendor_name" varchar(200),
	"address_id" uuid,
	"base_currency_id" uuid,
	"payment_terms" varchar(255),
	"gstin" text,
	"pan_number" text,
	"bank_name" text,
	"bank_account_number" text,
	"bank_ifsc" text,
	"contact_email" text,
	"contact_phone" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "vendor_code" varchar(50);
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "vendor_name" varchar(200);
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "address_id" uuid;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "base_currency_id" uuid;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "payment_terms" varchar(255);
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "gstin" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "pan_number" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "bank_name" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "bank_account_number" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "bank_ifsc" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "contact_email" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "contact_phone" text;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_details" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_po_ack" (
	"vendor_po_ack_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"purchase_order_id" uuid,
	"vendor_id" uuid,
	"acknowledged_dt" timestamp with time zone,
	"accepted_delivery_date" date,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "acknowledged_dt" timestamp with time zone;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "accepted_delivery_date" date;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_po_ack" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "procurement"."vendor_rm_mapping" (
	"vendor_rm_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"vendor_id" uuid,
	"material_id" uuid,
	"is_preferred" boolean,
	"lead_time_days" integer,
	"min_order_qty" numeric(18, 3),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "is_preferred" boolean;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "lead_time_days" integer;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "min_order_qty" numeric(18, 3);
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "procurement"."vendor_rm_mapping" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "procurement"."po_approval_order" ADD CONSTRAINT "po_approval_order_purchase_order_id_purchase_order_purchase_order_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "procurement"."purchase_order"("purchase_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."purchase_order" ADD CONSTRAINT "purchase_order_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."purchase_order" ADD CONSTRAINT "purchase_order_replacement_of_po_id_purchase_order_purchase_order_id_fk" FOREIGN KEY ("replacement_of_po_id") REFERENCES "procurement"."purchase_order"("purchase_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."purchase_order_items" ADD CONSTRAINT "purchase_order_items_purchase_order_id_purchase_order_purchase_order_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "procurement"."purchase_order"("purchase_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."purchase_request_approval" ADD CONSTRAINT "purchase_request_approval_purchase_request_id_purchase_request_purchase_request_id_fk" FOREIGN KEY ("purchase_request_id") REFERENCES "procurement"."purchase_request"("purchase_request_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."purchase_request_items" ADD CONSTRAINT "purchase_request_items_purchase_request_id_purchase_request_purchase_request_id_fk" FOREIGN KEY ("purchase_request_id") REFERENCES "procurement"."purchase_request"("purchase_request_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."quotation_items" ADD CONSTRAINT "quotation_items_quotation_id_quotations_quotation_id_fk" FOREIGN KEY ("quotation_id") REFERENCES "procurement"."quotations"("quotation_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."quotations" ADD CONSTRAINT "quotations_rfq_id_rfq_master_rfq_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "procurement"."rfq_master"("rfq_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."quotations" ADD CONSTRAINT "quotations_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."rfq_items" ADD CONSTRAINT "rfq_items_rfq_id_rfq_master_rfq_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "procurement"."rfq_master"("rfq_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."rfq_vendor_mappings" ADD CONSTRAINT "rfq_vendor_mappings_rfq_id_rfq_master_rfq_id_fk" FOREIGN KEY ("rfq_id") REFERENCES "procurement"."rfq_master"("rfq_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."rfq_vendor_mappings" ADD CONSTRAINT "rfq_vendor_mappings_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."stock_req_items" ADD CONSTRAINT "stock_req_items_stock_requirement_id_stock_requirement_stock_requirement_id_fk" FOREIGN KEY ("stock_requirement_id") REFERENCES "procurement"."stock_requirement"("stock_requirement_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_contact" ADD CONSTRAINT "vendor_contact_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_credit_note" ADD CONSTRAINT "vendor_credit_note_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_credit_note" ADD CONSTRAINT "vendor_credit_note_vendor_credit_reason_id_vendor_credit_reason_master_vendor_credit_reason_id_fk" FOREIGN KEY ("vendor_credit_reason_id") REFERENCES "procurement"."vendor_credit_reason_master"("vendor_credit_reason_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_credit_notes_allocation" ADD CONSTRAINT "vendor_credit_notes_allocation_vendor_credit_note_id_vendor_credit_note_vendor_credit_note_id_fk" FOREIGN KEY ("vendor_credit_note_id") REFERENCES "procurement"."vendor_credit_note"("vendor_credit_note_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_po_ack" ADD CONSTRAINT "vendor_po_ack_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "procurement"."vendor_rm_mapping" ADD CONSTRAINT "vendor_rm_mapping_vendor_id_vendor_details_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "procurement"."vendor_details"("vendor_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "procurement"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "procurement"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "procurement"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "procurement"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "procurement"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "procurement"."outbox" USING btree ("occurred_at","seq") WHERE "procurement"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "procurement"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "po_approval_order_po_idx" ON "procurement"."po_approval_order" USING btree ("purchase_order_id");
CREATE UNIQUE INDEX IF NOT EXISTS "purchase_order_po_number_uq" ON "procurement"."purchase_order" USING btree ("po_number");
CREATE INDEX IF NOT EXISTS "purchase_order_vendor_idx" ON "procurement"."purchase_order" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "purchase_order_replacement_of_po_idx" ON "procurement"."purchase_order" USING btree ("replacement_of_po_id");
CREATE INDEX IF NOT EXISTS "purchase_order_items_po_idx" ON "procurement"."purchase_order_items" USING btree ("purchase_order_id");
CREATE UNIQUE INDEX IF NOT EXISTS "purchase_request_pr_number_uq" ON "procurement"."purchase_request" USING btree ("pr_number");
CREATE INDEX IF NOT EXISTS "purchase_request_approval_pr_idx" ON "procurement"."purchase_request_approval" USING btree ("purchase_request_id");
CREATE INDEX IF NOT EXISTS "purchase_request_items_pr_idx" ON "procurement"."purchase_request_items" USING btree ("purchase_request_id");
CREATE INDEX IF NOT EXISTS "quotation_items_quotation_idx" ON "procurement"."quotation_items" USING btree ("quotation_id");
CREATE UNIQUE INDEX IF NOT EXISTS "quotations_quotation_number_uq" ON "procurement"."quotations" USING btree ("quotation_number");
CREATE INDEX IF NOT EXISTS "quotations_rfq_idx" ON "procurement"."quotations" USING btree ("rfq_id");
CREATE INDEX IF NOT EXISTS "quotations_vendor_idx" ON "procurement"."quotations" USING btree ("vendor_id");
CREATE UNIQUE INDEX IF NOT EXISTS "quotations_rfq_selected_uq" ON "procurement"."quotations" USING btree ("rfq_id") WHERE status = 'SELECTED';
CREATE INDEX IF NOT EXISTS "rfq_items_rfq_idx" ON "procurement"."rfq_items" USING btree ("rfq_id");
CREATE UNIQUE INDEX IF NOT EXISTS "rfq_master_rfq_number_uq" ON "procurement"."rfq_master" USING btree ("rfq_number");
CREATE INDEX IF NOT EXISTS "rfq_vendor_mappings_rfq_idx" ON "procurement"."rfq_vendor_mappings" USING btree ("rfq_id");
CREATE INDEX IF NOT EXISTS "rfq_vendor_mappings_vendor_idx" ON "procurement"."rfq_vendor_mappings" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "stock_req_items_req_idx" ON "procurement"."stock_req_items" USING btree ("stock_requirement_id");
CREATE INDEX IF NOT EXISTS "stock_requirement_location_idx" ON "procurement"."stock_requirement" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "stock_requirement_material_idx" ON "procurement"."stock_requirement" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "vendor_contact_vendor_idx" ON "procurement"."vendor_contact" USING btree ("vendor_id");
CREATE UNIQUE INDEX IF NOT EXISTS "vendor_credit_note_number_uq" ON "procurement"."vendor_credit_note" USING btree ("credit_note_number");
CREATE INDEX IF NOT EXISTS "vendor_credit_note_vendor_idx" ON "procurement"."vendor_credit_note" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_credit_note_reason_idx" ON "procurement"."vendor_credit_note" USING btree ("vendor_credit_reason_id");
CREATE INDEX IF NOT EXISTS "vendor_credit_notes_allocation_note_idx" ON "procurement"."vendor_credit_notes_allocation" USING btree ("vendor_credit_note_id");
CREATE UNIQUE INDEX IF NOT EXISTS "vendor_credit_reason_master_code_uq" ON "procurement"."vendor_credit_reason_master" USING btree ("reason_code");
CREATE UNIQUE INDEX IF NOT EXISTS "vendor_details_code_uq" ON "procurement"."vendor_details" USING btree ("vendor_code");
CREATE INDEX IF NOT EXISTS "vendor_details_org_idx" ON "procurement"."vendor_details" USING btree ("organization_id");
CREATE INDEX IF NOT EXISTS "vendor_po_ack_po_idx" ON "procurement"."vendor_po_ack" USING btree ("purchase_order_id");
CREATE INDEX IF NOT EXISTS "vendor_po_ack_vendor_idx" ON "procurement"."vendor_po_ack" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_rm_mapping_vendor_idx" ON "procurement"."vendor_rm_mapping" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "vendor_rm_mapping_material_idx" ON "procurement"."vendor_rm_mapping" USING btree ("material_id");
