-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-inventory.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "inventory";

CREATE TABLE IF NOT EXISTS "inventory"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "inventory"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "inventory"."batch_container_mappings" (
	"batch_container_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rm_batch_id" uuid,
	"grn_container_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "grn_container_id" uuid;
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."batch_container_mappings" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."batch_genealogy_history" (
	"batch_genealogy_history_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"finished_good_batch_id" uuid,
	"oil_batch_id" uuid,
	"rm_batch_id" uuid,
	"relationship_type" varchar(30),
	"recorded_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "relationship_type" varchar(30);
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "recorded_dt" timestamp with time zone;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."batch_genealogy_history" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."expiry_tracker" (
	"expiry_tracker_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"batch_type" varchar(30) NOT NULL,
	"rm_batch_id" uuid,
	"oil_batch_id" uuid,
	"finished_good_batch_id" uuid,
	"material_id" uuid,
	"manufacturing_date" date,
	"expiry_date" date,
	"remaining_days" integer,
	"alert_threshold_days" integer,
	"alert_sent_dt" timestamp with time zone,
	"alert_sent_to" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "batch_type" varchar(30);  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "manufacturing_date" date;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "expiry_date" date;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "remaining_days" integer;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "alert_threshold_days" integer;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "alert_sent_dt" timestamp with time zone;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "alert_sent_to" uuid;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."expiry_tracker" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."gate_entry_documents" (
	"gate_entry_document_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"gate_entry_id" uuid,
	"document_type_id" uuid,
	"document_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "gate_entry_id" uuid;
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "document_type_id" uuid;
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "document_id" uuid;
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."gate_entry_documents" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."gate_entry_master" (
	"gate_entry_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"gate_entry_number" varchar(50),
	"vendor_id" uuid,
	"purchase_order_id" uuid,
	"location_id" uuid,
	"vehicle_number" varchar(20),
	"entry_dt" timestamp with time zone,
	"exit_dt" timestamp with time zone,
	"driver_name" varchar(200),
	"invoice_number" text,
	"challan_number" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "gate_entry_number" varchar(50);
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "vehicle_number" varchar(20);
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "entry_dt" timestamp with time zone;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "exit_dt" timestamp with time zone;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "driver_name" varchar(200);
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "invoice_number" text;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "challan_number" text;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."gate_entry_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."grn_container" (
	"grn_container_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"grn_id" uuid,
	"grn_item_id" uuid,
	"container_code" varchar(50),
	"container_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "grn_id" uuid;
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "grn_item_id" uuid;
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "container_code" varchar(50);
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "container_qty" numeric(18, 4);
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."grn_container" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."grn_items" (
	"grn_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"grn_id" uuid,
	"purchase_order_item_id" uuid,
	"material_id" uuid,
	"received_qty" numeric(18, 4),
	"uom_id" uuid,
	"accepted_qty" numeric(18, 4),
	"rejected_qty" numeric(18, 4),
	"ordered_qty" numeric(18, 3),
	"damaged_qty" numeric(18, 3),
	"variance_qty" numeric(18, 3),
	"variance_type" text,
	"variance_reason" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "grn_id" uuid;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "purchase_order_item_id" uuid;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "received_qty" numeric(18, 4);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "accepted_qty" numeric(18, 4);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "rejected_qty" numeric(18, 4);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "ordered_qty" numeric(18, 3);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "damaged_qty" numeric(18, 3);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "variance_qty" numeric(18, 3);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "variance_type" text;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "variance_reason" text;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."grn_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."grn_master" (
	"grn_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"grn_number" varchar(50),
	"gate_entry_id" uuid,
	"purchase_order_id" uuid,
	"vendor_id" uuid,
	"location_id" uuid,
	"grn_date" date,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "grn_number" varchar(50);
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "gate_entry_id" uuid;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "purchase_order_id" uuid;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "vendor_id" uuid;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "grn_date" date;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."grn_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."inventory_batch" (
	"inventory_batch_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rm_batch_id" uuid,
	"material_id" uuid,
	"storage_location_id" uuid,
	"inventory_status_id" uuid,
	"quantity_on_hand" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "storage_location_id" uuid;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "inventory_status_id" uuid;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "quantity_on_hand" numeric(18, 4);
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."inventory_batch" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."inventory_event_history" (
	"inventory_event_history_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"inventory_batch_id" uuid,
	"event_type" varchar(50),
	"event_dt" timestamp with time zone,
	"inventory_transaction_id" uuid,
	"reference_document_id" uuid,
	"reference_document_type" varchar(50),
	"event_qty" numeric(18, 4),
	"performed_by" uuid,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "event_type" varchar(50);
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "event_dt" timestamp with time zone;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "inventory_transaction_id" uuid;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "reference_document_id" uuid;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "reference_document_type" varchar(50);
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "event_qty" numeric(18, 4);
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "performed_by" uuid;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."inventory_event_history" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."inventory_status_master" (
	"inventory_status_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"status_code" varchar(50),
	"status_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "status_code" varchar(50);
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "status_name" varchar(200);
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."inventory_status_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."inventory_transaction" (
	"inventory_transaction_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"inventory_batch_id" uuid,
	"inventory_transaction_type_id" uuid,
	"transaction_qty" numeric(18, 4),
	"uom_id" uuid,
	"from_location_id" uuid,
	"to_location_id" uuid,
	"transaction_dt" timestamp with time zone,
	"reference_document_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "inventory_transaction_type_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "transaction_qty" numeric(18, 4);
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "from_location_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "to_location_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "transaction_dt" timestamp with time zone;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "reference_document_id" uuid;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."inventory_transaction" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."inventory_transaction_type_master" (
	"inventory_transaction_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."inventory_transaction_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "inventory"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "inventory"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "inventory"."rm_batch_master" (
	"rm_batch_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"grn_item_id" uuid,
	"material_id" uuid,
	"batch_number" varchar(50),
	"manufacturing_date" date,
	"expiry_date" date,
	"received_qty" numeric(18, 4),
	"uom_id" uuid,
	"storage_location_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "grn_item_id" uuid;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "batch_number" varchar(50);
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "manufacturing_date" date;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "expiry_date" date;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "received_qty" numeric(18, 4);
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "storage_location_id" uuid;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."rm_batch_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."stock_adjustment" (
	"stock_adjustment_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"inventory_batch_id" uuid,
	"adjustment_qty" numeric(18, 4),
	"uom_id" uuid,
	"adjustment_reason" text,
	"adjustment_dt" timestamp with time zone,
	"approved_by" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "adjustment_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "adjustment_reason" text;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "adjustment_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "approved_by" uuid;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."stock_adjustment" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."stock_audit" (
	"stock_audit_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"audit_code" varchar(50),
	"audit_type" varchar(30),
	"location_id" uuid,
	"audit_start_dt" timestamp with time zone,
	"audit_end_dt" timestamp with time zone,
	"initiated_by" uuid,
	"approved_by" uuid,
	"approved_dt" timestamp with time zone,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "audit_code" varchar(50);
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "audit_type" varchar(30);
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "audit_start_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "audit_end_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "initiated_by" uuid;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "approved_by" uuid;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."stock_audit" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."stock_audit_details" (
	"stock_audit_detail_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"stock_audit_id" uuid,
	"material_id" uuid,
	"inventory_batch_id" uuid,
	"storage_location_id" uuid,
	"system_qty" numeric(18, 4),
	"counted_qty" numeric(18, 4),
	"variance_qty" numeric(18, 4),
	"uom_id" uuid,
	"counted_by" uuid,
	"counted_dt" timestamp with time zone,
	"variance_reason" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "stock_audit_id" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "storage_location_id" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "system_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "counted_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "variance_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "counted_by" uuid;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "counted_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "variance_reason" text;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."stock_audit_details" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."stock_reservation" (
	"stock_reservation_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"inventory_batch_id" uuid,
	"reserved_qty" numeric(18, 4),
	"uom_id" uuid,
	"reserved_for_document_id" uuid,
	"reserved_dt" timestamp with time zone,
	"released_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "reserved_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "reserved_for_document_id" uuid;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "reserved_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "released_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."stock_reservation" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "inventory"."stock_transfer" (
	"stock_transfer_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"inventory_batch_id" uuid,
	"from_location_id" uuid,
	"to_location_id" uuid,
	"transfer_qty" numeric(18, 4),
	"uom_id" uuid,
	"transfer_dt" timestamp with time zone,
	"requested_by" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "from_location_id" uuid;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "to_location_id" uuid;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "transfer_qty" numeric(18, 4);
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "transfer_dt" timestamp with time zone;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "requested_by" uuid;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "inventory"."stock_transfer" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "inventory"."gate_entry_documents" ADD CONSTRAINT "gate_entry_documents_gate_entry_id_gate_entry_master_gate_entry_id_fk" FOREIGN KEY ("gate_entry_id") REFERENCES "inventory"."gate_entry_master"("gate_entry_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."grn_container" ADD CONSTRAINT "grn_container_grn_id_grn_master_grn_id_fk" FOREIGN KEY ("grn_id") REFERENCES "inventory"."grn_master"("grn_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."grn_container" ADD CONSTRAINT "grn_container_grn_item_id_grn_items_grn_item_id_fk" FOREIGN KEY ("grn_item_id") REFERENCES "inventory"."grn_items"("grn_item_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."grn_items" ADD CONSTRAINT "grn_items_grn_id_grn_master_grn_id_fk" FOREIGN KEY ("grn_id") REFERENCES "inventory"."grn_master"("grn_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."inventory_batch" ADD CONSTRAINT "inventory_batch_inventory_status_id_inventory_status_master_inventory_status_id_fk" FOREIGN KEY ("inventory_status_id") REFERENCES "inventory"."inventory_status_master"("inventory_status_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."inventory_transaction" ADD CONSTRAINT "inventory_transaction_inventory_batch_id_inventory_batch_inventory_batch_id_fk" FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory"."inventory_batch"("inventory_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."inventory_transaction" ADD CONSTRAINT "inventory_transaction_inventory_transaction_type_id_inventory_transaction_type_master_inventory_transaction_type_id_fk" FOREIGN KEY ("inventory_transaction_type_id") REFERENCES "inventory"."inventory_transaction_type_master"("inventory_transaction_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."stock_adjustment" ADD CONSTRAINT "stock_adjustment_inventory_batch_id_inventory_batch_inventory_batch_id_fk" FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory"."inventory_batch"("inventory_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."stock_audit_details" ADD CONSTRAINT "stock_audit_details_stock_audit_id_stock_audit_stock_audit_id_fk" FOREIGN KEY ("stock_audit_id") REFERENCES "inventory"."stock_audit"("stock_audit_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."stock_reservation" ADD CONSTRAINT "stock_reservation_inventory_batch_id_inventory_batch_inventory_batch_id_fk" FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory"."inventory_batch"("inventory_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "inventory"."stock_transfer" ADD CONSTRAINT "stock_transfer_inventory_batch_id_inventory_batch_inventory_batch_id_fk" FOREIGN KEY ("inventory_batch_id") REFERENCES "inventory"."inventory_batch"("inventory_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "inventory"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "inventory"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "inventory"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "inventory"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "inventory"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "batch_container_mappings_rm_batch_idx" ON "inventory"."batch_container_mappings" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "batch_container_mappings_grn_container_idx" ON "inventory"."batch_container_mappings" USING btree ("grn_container_id");
CREATE INDEX IF NOT EXISTS "batch_genealogy_history_fg_batch_idx" ON "inventory"."batch_genealogy_history" USING btree ("finished_good_batch_id");
CREATE INDEX IF NOT EXISTS "batch_genealogy_history_oil_batch_idx" ON "inventory"."batch_genealogy_history" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "batch_genealogy_history_rm_batch_idx" ON "inventory"."batch_genealogy_history" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "expiry_tracker_rm_batch_idx" ON "inventory"."expiry_tracker" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "expiry_tracker_oil_batch_idx" ON "inventory"."expiry_tracker" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "expiry_tracker_fg_batch_idx" ON "inventory"."expiry_tracker" USING btree ("finished_good_batch_id");
CREATE INDEX IF NOT EXISTS "expiry_tracker_material_idx" ON "inventory"."expiry_tracker" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "expiry_tracker_alert_sent_to_idx" ON "inventory"."expiry_tracker" USING btree ("alert_sent_to");
CREATE INDEX IF NOT EXISTS "gate_entry_documents_gate_entry_idx" ON "inventory"."gate_entry_documents" USING btree ("gate_entry_id");
CREATE INDEX IF NOT EXISTS "gate_entry_documents_document_type_idx" ON "inventory"."gate_entry_documents" USING btree ("document_type_id");
CREATE INDEX IF NOT EXISTS "gate_entry_documents_document_idx" ON "inventory"."gate_entry_documents" USING btree ("document_id");
CREATE UNIQUE INDEX IF NOT EXISTS "gate_entry_master_number_uq" ON "inventory"."gate_entry_master" USING btree ("gate_entry_number");
CREATE INDEX IF NOT EXISTS "gate_entry_master_vendor_idx" ON "inventory"."gate_entry_master" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "gate_entry_master_po_idx" ON "inventory"."gate_entry_master" USING btree ("purchase_order_id");
CREATE INDEX IF NOT EXISTS "gate_entry_master_location_idx" ON "inventory"."gate_entry_master" USING btree ("location_id");
CREATE UNIQUE INDEX IF NOT EXISTS "grn_container_code_uq" ON "inventory"."grn_container" USING btree ("container_code");
CREATE INDEX IF NOT EXISTS "grn_container_grn_idx" ON "inventory"."grn_container" USING btree ("grn_id");
CREATE INDEX IF NOT EXISTS "grn_container_grn_item_idx" ON "inventory"."grn_container" USING btree ("grn_item_id");
CREATE INDEX IF NOT EXISTS "grn_container_uom_idx" ON "inventory"."grn_container" USING btree ("uom_id");
CREATE INDEX IF NOT EXISTS "grn_items_grn_idx" ON "inventory"."grn_items" USING btree ("grn_id");
CREATE INDEX IF NOT EXISTS "grn_items_po_item_idx" ON "inventory"."grn_items" USING btree ("purchase_order_item_id");
CREATE INDEX IF NOT EXISTS "grn_items_material_idx" ON "inventory"."grn_items" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "grn_items_uom_idx" ON "inventory"."grn_items" USING btree ("uom_id");
CREATE UNIQUE INDEX IF NOT EXISTS "grn_master_number_uq" ON "inventory"."grn_master" USING btree ("grn_number");
CREATE INDEX IF NOT EXISTS "grn_master_gate_entry_idx" ON "inventory"."grn_master" USING btree ("gate_entry_id");
CREATE INDEX IF NOT EXISTS "grn_master_po_idx" ON "inventory"."grn_master" USING btree ("purchase_order_id");
CREATE INDEX IF NOT EXISTS "grn_master_vendor_idx" ON "inventory"."grn_master" USING btree ("vendor_id");
CREATE INDEX IF NOT EXISTS "grn_master_location_idx" ON "inventory"."grn_master" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "inventory_batch_rm_batch_idx" ON "inventory"."inventory_batch" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "inventory_batch_material_idx" ON "inventory"."inventory_batch" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "inventory_batch_storage_location_idx" ON "inventory"."inventory_batch" USING btree ("storage_location_id");
CREATE INDEX IF NOT EXISTS "inventory_batch_status_idx" ON "inventory"."inventory_batch" USING btree ("inventory_status_id");
CREATE INDEX IF NOT EXISTS "inventory_batch_uom_idx" ON "inventory"."inventory_batch" USING btree ("uom_id");
CREATE INDEX IF NOT EXISTS "inventory_event_history_batch_idx" ON "inventory"."inventory_event_history" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "inventory_event_history_transaction_idx" ON "inventory"."inventory_event_history" USING btree ("inventory_transaction_id");
CREATE INDEX IF NOT EXISTS "inventory_event_history_reference_document_idx" ON "inventory"."inventory_event_history" USING btree ("reference_document_id");
CREATE INDEX IF NOT EXISTS "inventory_event_history_performed_by_idx" ON "inventory"."inventory_event_history" USING btree ("performed_by");
CREATE UNIQUE INDEX IF NOT EXISTS "inventory_status_master_code_uq" ON "inventory"."inventory_status_master" USING btree ("status_code");
CREATE INDEX IF NOT EXISTS "inventory_transaction_batch_idx" ON "inventory"."inventory_transaction" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "inventory_transaction_type_idx" ON "inventory"."inventory_transaction" USING btree ("inventory_transaction_type_id");
CREATE INDEX IF NOT EXISTS "inventory_transaction_from_location_idx" ON "inventory"."inventory_transaction" USING btree ("from_location_id");
CREATE INDEX IF NOT EXISTS "inventory_transaction_to_location_idx" ON "inventory"."inventory_transaction" USING btree ("to_location_id");
CREATE INDEX IF NOT EXISTS "inventory_transaction_reference_document_idx" ON "inventory"."inventory_transaction" USING btree ("reference_document_id");
CREATE UNIQUE INDEX IF NOT EXISTS "inventory_transaction_type_master_code_uq" ON "inventory"."inventory_transaction_type_master" USING btree ("type_code");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "inventory"."outbox" USING btree ("occurred_at","seq") WHERE "inventory"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "inventory"."outbox" USING btree ("aggregate_id");
CREATE UNIQUE INDEX IF NOT EXISTS "rm_batch_master_number_uq" ON "inventory"."rm_batch_master" USING btree ("batch_number");
CREATE INDEX IF NOT EXISTS "rm_batch_master_grn_item_idx" ON "inventory"."rm_batch_master" USING btree ("grn_item_id");
CREATE INDEX IF NOT EXISTS "rm_batch_master_material_idx" ON "inventory"."rm_batch_master" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "rm_batch_master_storage_location_idx" ON "inventory"."rm_batch_master" USING btree ("storage_location_id");
CREATE INDEX IF NOT EXISTS "stock_adjustment_batch_idx" ON "inventory"."stock_adjustment" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "stock_adjustment_uom_idx" ON "inventory"."stock_adjustment" USING btree ("uom_id");
CREATE INDEX IF NOT EXISTS "stock_adjustment_approved_by_idx" ON "inventory"."stock_adjustment" USING btree ("approved_by");
CREATE UNIQUE INDEX IF NOT EXISTS "stock_audit_code_uq" ON "inventory"."stock_audit" USING btree ("audit_code");
CREATE INDEX IF NOT EXISTS "stock_audit_location_idx" ON "inventory"."stock_audit" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "stock_audit_initiated_by_idx" ON "inventory"."stock_audit" USING btree ("initiated_by");
CREATE INDEX IF NOT EXISTS "stock_audit_approved_by_idx" ON "inventory"."stock_audit" USING btree ("approved_by");
CREATE INDEX IF NOT EXISTS "stock_audit_details_audit_idx" ON "inventory"."stock_audit_details" USING btree ("stock_audit_id");
CREATE INDEX IF NOT EXISTS "stock_audit_details_material_idx" ON "inventory"."stock_audit_details" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "stock_audit_details_batch_idx" ON "inventory"."stock_audit_details" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "stock_audit_details_storage_location_idx" ON "inventory"."stock_audit_details" USING btree ("storage_location_id");
CREATE INDEX IF NOT EXISTS "stock_audit_details_counted_by_idx" ON "inventory"."stock_audit_details" USING btree ("counted_by");
CREATE INDEX IF NOT EXISTS "stock_reservation_batch_idx" ON "inventory"."stock_reservation" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "stock_reservation_document_idx" ON "inventory"."stock_reservation" USING btree ("reserved_for_document_id");
CREATE INDEX IF NOT EXISTS "stock_transfer_batch_idx" ON "inventory"."stock_transfer" USING btree ("inventory_batch_id");
CREATE INDEX IF NOT EXISTS "stock_transfer_from_location_idx" ON "inventory"."stock_transfer" USING btree ("from_location_id");
CREATE INDEX IF NOT EXISTS "stock_transfer_to_location_idx" ON "inventory"."stock_transfer" USING btree ("to_location_id");
CREATE INDEX IF NOT EXISTS "stock_transfer_requested_by_idx" ON "inventory"."stock_transfer" USING btree ("requested_by");
