-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-quality.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "quality";

CREATE TABLE IF NOT EXISTS "quality"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "quality"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "quality"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "quality"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "quality"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "quality"."qc_attachments" (
	"qc_attachment_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"qc_inspection_id" uuid,
	"document_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "qc_inspection_id" uuid;
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "document_id" uuid;
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_attachments" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_capa" (
	"qc_capa_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"qc_inspection_id" uuid,
	"capa_code" varchar(50),
	"capa_type" varchar(30),
	"description" text,
	"root_cause" text,
	"action_plan" text,
	"assigned_to" uuid,
	"due_dt" timestamp with time zone,
	"closed_dt" timestamp with time zone,
	"closure_evidence" text,
	"verified_by" uuid,
	"verified_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "qc_inspection_id" uuid;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "capa_code" varchar(50);
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "capa_type" varchar(30);
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "root_cause" text;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "action_plan" text;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "assigned_to" uuid;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "due_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "closed_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "closure_evidence" text;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "verified_by" uuid;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "verified_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_capa" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_disposition" (
	"qc_disposition_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"qc_inspection_id" uuid,
	"disposition_code" varchar(50),
	"disposition_reason" text,
	"conditions" text,
	"disposed_by" uuid,
	"disposed_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "qc_inspection_id" uuid;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "disposition_code" varchar(50);
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "disposition_reason" text;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "conditions" text;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "disposed_by" uuid;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "disposed_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_disposition" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_inspections" (
	"qc_inspection_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"rm_batch_id" uuid,
	"inspection_role_id" uuid,
	"inspector_user_id" uuid,
	"inspection_dt" timestamp with time zone,
	"overall_result" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "inspection_role_id" uuid;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "inspector_user_id" uuid;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "inspection_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "overall_result" varchar(255);
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_inspections" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_parameter_master" (
	"qc_parameter_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"parameter_code" varchar(50),
	"parameter_name" varchar(200),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "parameter_code" varchar(50);
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "parameter_name" varchar(200);
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_parameter_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_result_details" (
	"qc_result_detail_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"qc_inspection_id" uuid,
	"qc_parameter_id" uuid,
	"observed_value" numeric(18, 4),
	"observed_text" text,
	"result" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "qc_inspection_id" uuid;
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "qc_parameter_id" uuid;
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "observed_value" numeric(18, 4);
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "observed_text" text;
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "result" varchar(255);
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_result_details" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "quality"."qc_sample_retention" (
	"qc_sample_retention_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"qc_inspection_id" uuid,
	"rm_batch_id" uuid,
	"oil_batch_id" uuid,
	"sample_code" varchar(50),
	"sample_qty" numeric(18, 4),
	"uom_id" uuid,
	"retention_location_id" uuid,
	"retained_dt" timestamp with time zone,
	"retained_by" uuid,
	"retention_expiry_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "qc_inspection_id" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "rm_batch_id" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "sample_code" varchar(50);
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "sample_qty" numeric(18, 4);
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "retention_location_id" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "retained_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "retained_by" uuid;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "retention_expiry_dt" timestamp with time zone;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "quality"."qc_sample_retention" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "quality"."qc_attachments" ADD CONSTRAINT "qc_attachments_qc_inspection_id_qc_inspections_qc_inspection_id_fk" FOREIGN KEY ("qc_inspection_id") REFERENCES "quality"."qc_inspections"("qc_inspection_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "quality"."qc_disposition" ADD CONSTRAINT "qc_disposition_qc_inspection_id_qc_inspections_qc_inspection_id_fk" FOREIGN KEY ("qc_inspection_id") REFERENCES "quality"."qc_inspections"("qc_inspection_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "quality"."qc_result_details" ADD CONSTRAINT "qc_result_details_qc_inspection_id_qc_inspections_qc_inspection_id_fk" FOREIGN KEY ("qc_inspection_id") REFERENCES "quality"."qc_inspections"("qc_inspection_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "quality"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "quality"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "quality"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "quality"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "quality"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "quality"."outbox" USING btree ("occurred_at","seq") WHERE "quality"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "quality"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "qc_attachments_inspection_idx" ON "quality"."qc_attachments" USING btree ("qc_inspection_id");
CREATE INDEX IF NOT EXISTS "qc_attachments_document_idx" ON "quality"."qc_attachments" USING btree ("document_id");
CREATE UNIQUE INDEX IF NOT EXISTS "qc_capa_code_uq" ON "quality"."qc_capa" USING btree ("capa_code");
CREATE INDEX IF NOT EXISTS "qc_capa_inspection_idx" ON "quality"."qc_capa" USING btree ("qc_inspection_id");
CREATE INDEX IF NOT EXISTS "qc_disposition_inspection_idx" ON "quality"."qc_disposition" USING btree ("qc_inspection_id");
CREATE INDEX IF NOT EXISTS "qc_inspections_rm_batch_idx" ON "quality"."qc_inspections" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "qc_inspections_role_idx" ON "quality"."qc_inspections" USING btree ("inspection_role_id");
CREATE INDEX IF NOT EXISTS "qc_inspections_inspector_idx" ON "quality"."qc_inspections" USING btree ("inspector_user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "qc_parameter_master_code_uq" ON "quality"."qc_parameter_master" USING btree ("parameter_code");
CREATE INDEX IF NOT EXISTS "qc_parameter_master_uom_idx" ON "quality"."qc_parameter_master" USING btree ("uom_id");
CREATE INDEX IF NOT EXISTS "qc_result_details_inspection_idx" ON "quality"."qc_result_details" USING btree ("qc_inspection_id");
CREATE INDEX IF NOT EXISTS "qc_result_details_parameter_idx" ON "quality"."qc_result_details" USING btree ("qc_parameter_id");
CREATE UNIQUE INDEX IF NOT EXISTS "qc_sample_retention_code_uq" ON "quality"."qc_sample_retention" USING btree ("sample_code");
CREATE INDEX IF NOT EXISTS "qc_sample_retention_inspection_idx" ON "quality"."qc_sample_retention" USING btree ("qc_inspection_id");
CREATE INDEX IF NOT EXISTS "qc_sample_retention_rm_batch_idx" ON "quality"."qc_sample_retention" USING btree ("rm_batch_id");
CREATE INDEX IF NOT EXISTS "qc_sample_retention_oil_batch_idx" ON "quality"."qc_sample_retention" USING btree ("oil_batch_id");
