-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-production.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "production";

CREATE TABLE IF NOT EXISTS "production"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "production"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "production"."material_issue" (
	"material_issue_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_order_id" uuid,
	"material_pick_list_id" uuid,
	"issued_dt" timestamp with time zone,
	"issued_by" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "material_pick_list_id" uuid;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "issued_dt" timestamp with time zone;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "issued_by" uuid;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."material_issue" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."material_issue_item" (
	"material_issue_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_issue_id" uuid,
	"material_id" uuid,
	"inventory_batch_id" uuid,
	"issued_qty" boolean,
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "material_issue_id" uuid;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "issued_qty" boolean;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."material_issue_item" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."material_pick_list" (
	"material_pick_list_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_order_id" uuid,
	"pick_list_date" date,
	"generated_by" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "pick_list_date" date;
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "generated_by" uuid;
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."material_pick_list" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."material_pick_list_items" (
	"material_pick_list_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"material_pick_list_id" uuid,
	"material_id" uuid,
	"inventory_batch_id" uuid,
	"picked_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "material_pick_list_id" uuid;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "inventory_batch_id" uuid;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "picked_qty" numeric(18, 4);
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."material_pick_list_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."mixing_step_log" (
	"mixing_step_log_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"secure_mixing_session_id" uuid,
	"formula_stage_id" uuid,
	"step_sequence" integer,
	"step_description" text,
	"performed_dt" timestamp with time zone,
	"performed_by" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "secure_mixing_session_id" uuid;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "formula_stage_id" uuid;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "step_sequence" integer;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "step_description" text;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "performed_dt" timestamp with time zone;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "performed_by" uuid;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."mixing_step_log" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."oil_batch_consumption" (
	"oil_batch_consumption_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"oil_batch_id" uuid,
	"consumed_for_document_id" uuid,
	"consumed_qty" numeric(18, 4),
	"uom_id" uuid,
	"consumed_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_for_document_id" uuid;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_qty" numeric(18, 4);
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_dt" timestamp with time zone;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."oil_batch_consumption" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."oil_batch_event_history" (
	"oil_batch_event_history_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"oil_batch_id" uuid,
	"event_type" varchar(30),
	"event_dt" timestamp with time zone,
	"performed_by" uuid,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "event_type" varchar(30);
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "event_dt" timestamp with time zone;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "performed_by" uuid;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."oil_batch_event_history" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."oil_batch_master" (
	"oil_batch_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_order_id" uuid,
	"secure_mixing_session_id" uuid,
	"batch_number" varchar(50),
	"produced_qty" numeric(18, 4),
	"uom_id" uuid,
	"produced_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "secure_mixing_session_id" uuid;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "batch_number" varchar(50);
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "produced_qty" numeric(18, 4);
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "produced_dt" timestamp with time zone;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."oil_batch_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."oil_batch_qc_history" (
	"oil_batch_qc_history_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"oil_batch_id" uuid,
	"production_qc_id" uuid,
	"recorded_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "production_qc_id" uuid;
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "recorded_dt" timestamp with time zone;
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."oil_batch_qc_history" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "production"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "production"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "production"."production_order" (
	"production_order_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_plan_item_id" uuid,
	"formula_version_id" uuid,
	"location_id" uuid,
	"order_qty" numeric(18, 4),
	"uom_id" uuid,
	"actual_start_dt" timestamp with time zone,
	"actual_end_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "production_plan_item_id" uuid;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "order_qty" numeric(18, 4);
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "actual_start_dt" timestamp with time zone;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "actual_end_dt" timestamp with time zone;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."production_order" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."production_order_ingredients" (
	"production_order_ingredient_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_order_id" uuid,
	"material_id" uuid,
	"required_qty" numeric(18, 4),
	"issued_qty" boolean,
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "material_id" uuid;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "issued_qty" boolean;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."production_order_ingredients" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."production_plan" (
	"production_plan_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"location_id" uuid,
	"plan_date" date,
	"planned_start_dt" timestamp with time zone,
	"planned_end_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "plan_date" date;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "planned_start_dt" timestamp with time zone;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "planned_end_dt" timestamp with time zone;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."production_plan" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."production_plan_items" (
	"production_plan_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_plan_id" uuid,
	"formula_id" uuid,
	"planned_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "production_plan_id" uuid;
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "planned_qty" numeric(18, 4);
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."production_plan_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."production_qc" (
	"production_qc_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"oil_batch_id" uuid,
	"qc_parameter_id" uuid,
	"observed_value" numeric(18, 4),
	"result" varchar(255),
	"inspected_by" uuid,
	"inspection_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "qc_parameter_id" uuid;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "observed_value" numeric(18, 4);
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "result" varchar(255);
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "inspected_by" uuid;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "inspection_dt" timestamp with time zone;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."production_qc" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "production"."secure_mixing_session" (
	"secure_mixing_session_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"production_order_id" uuid,
	"operator_id" uuid,
	"session_start_dt" timestamp with time zone,
	"session_end_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "operator_id" uuid;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "session_start_dt" timestamp with time zone;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "session_end_dt" timestamp with time zone;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "production"."secure_mixing_session" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "production"."material_issue_item" ADD CONSTRAINT "material_issue_item_material_issue_id_material_issue_material_issue_id_fk" FOREIGN KEY ("material_issue_id") REFERENCES "production"."material_issue"("material_issue_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."material_pick_list_items" ADD CONSTRAINT "material_pick_list_items_material_pick_list_id_material_pick_list_material_pick_list_id_fk" FOREIGN KEY ("material_pick_list_id") REFERENCES "production"."material_pick_list"("material_pick_list_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."mixing_step_log" ADD CONSTRAINT "mixing_step_log_secure_mixing_session_id_secure_mixing_session_secure_mixing_session_id_fk" FOREIGN KEY ("secure_mixing_session_id") REFERENCES "production"."secure_mixing_session"("secure_mixing_session_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."oil_batch_consumption" ADD CONSTRAINT "oil_batch_consumption_oil_batch_id_oil_batch_master_oil_batch_id_fk" FOREIGN KEY ("oil_batch_id") REFERENCES "production"."oil_batch_master"("oil_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."oil_batch_event_history" ADD CONSTRAINT "oil_batch_event_history_oil_batch_id_oil_batch_master_oil_batch_id_fk" FOREIGN KEY ("oil_batch_id") REFERENCES "production"."oil_batch_master"("oil_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."oil_batch_qc_history" ADD CONSTRAINT "oil_batch_qc_history_oil_batch_id_oil_batch_master_oil_batch_id_fk" FOREIGN KEY ("oil_batch_id") REFERENCES "production"."oil_batch_master"("oil_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."production_order_ingredients" ADD CONSTRAINT "production_order_ingredients_production_order_id_production_order_production_order_id_fk" FOREIGN KEY ("production_order_id") REFERENCES "production"."production_order"("production_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "production"."production_plan_items" ADD CONSTRAINT "production_plan_items_production_plan_id_production_plan_production_plan_id_fk" FOREIGN KEY ("production_plan_id") REFERENCES "production"."production_plan"("production_plan_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "production"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "production"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "production"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "production"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "production"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "material_issue_order_idx" ON "production"."material_issue" USING btree ("production_order_id");
CREATE INDEX IF NOT EXISTS "material_issue_pick_list_idx" ON "production"."material_issue" USING btree ("material_pick_list_id");
CREATE INDEX IF NOT EXISTS "material_issue_item_issue_idx" ON "production"."material_issue_item" USING btree ("material_issue_id");
CREATE INDEX IF NOT EXISTS "material_pick_list_order_idx" ON "production"."material_pick_list" USING btree ("production_order_id");
CREATE INDEX IF NOT EXISTS "material_pick_list_items_list_idx" ON "production"."material_pick_list_items" USING btree ("material_pick_list_id");
CREATE INDEX IF NOT EXISTS "material_pick_list_items_material_idx" ON "production"."material_pick_list_items" USING btree ("material_id");
CREATE INDEX IF NOT EXISTS "mixing_step_log_session_idx" ON "production"."mixing_step_log" USING btree ("secure_mixing_session_id");
CREATE INDEX IF NOT EXISTS "oil_batch_consumption_batch_idx" ON "production"."oil_batch_consumption" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "oil_batch_event_history_batch_idx" ON "production"."oil_batch_event_history" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "oil_batch_master_order_idx" ON "production"."oil_batch_master" USING btree ("production_order_id");
CREATE INDEX IF NOT EXISTS "oil_batch_master_session_idx" ON "production"."oil_batch_master" USING btree ("secure_mixing_session_id");
CREATE INDEX IF NOT EXISTS "oil_batch_master_batch_number_idx" ON "production"."oil_batch_master" USING btree ("batch_number");
CREATE INDEX IF NOT EXISTS "oil_batch_qc_history_oil_batch_idx" ON "production"."oil_batch_qc_history" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "oil_batch_qc_history_qc_idx" ON "production"."oil_batch_qc_history" USING btree ("production_qc_id");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "production"."outbox" USING btree ("occurred_at","seq") WHERE "production"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "production"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "production_order_plan_item_idx" ON "production"."production_order" USING btree ("production_plan_item_id");
CREATE INDEX IF NOT EXISTS "production_order_location_idx" ON "production"."production_order" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "production_order_ingredients_order_idx" ON "production"."production_order_ingredients" USING btree ("production_order_id");
CREATE INDEX IF NOT EXISTS "production_plan_location_idx" ON "production"."production_plan" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "production_plan_items_plan_idx" ON "production"."production_plan_items" USING btree ("production_plan_id");
CREATE INDEX IF NOT EXISTS "production_plan_items_formula_idx" ON "production"."production_plan_items" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "production_qc_oil_batch_idx" ON "production"."production_qc" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "production_qc_parameter_idx" ON "production"."production_qc" USING btree ("qc_parameter_id");
CREATE INDEX IF NOT EXISTS "secure_mixing_session_order_idx" ON "production"."secure_mixing_session" USING btree ("production_order_id");
