-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-packaging.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "packaging";

CREATE TABLE IF NOT EXISTS "packaging"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "packaging"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "packaging"."filling_session" (
	"filling_session_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"package_order_id" uuid,
	"operator_id" uuid,
	"session_start_dt" timestamp with time zone,
	"session_end_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "package_order_id" uuid;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "operator_id" uuid;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "session_start_dt" timestamp with time zone;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "session_end_dt" timestamp with time zone;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."filling_session" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."filling_session_details" (
	"filling_session_detail_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"filling_session_id" uuid,
	"filled_qty" numeric(18, 4),
	"uom_id" uuid,
	"rejected_qty" numeric(18, 4),
	"recorded_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "filling_session_id" uuid;
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "filled_qty" numeric(18, 4);
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "rejected_qty" numeric(18, 4);
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "recorded_dt" timestamp with time zone;
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."filling_session_details" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."finished_good_batch_master" (
	"finished_good_batch_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"package_order_id" uuid,
	"product_sku_id" uuid,
	"batch_number" varchar(50),
	"produced_qty" numeric(18, 4),
	"uom_id" uuid,
	"manufacturing_date" date,
	"expiry_date" date,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "package_order_id" uuid;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "product_sku_id" uuid;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "batch_number" varchar(50);
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "produced_qty" numeric(18, 4);
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "manufacturing_date" date;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "expiry_date" date;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."finished_good_batch_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."finished_good_reservation" (
	"finished_good_reservation_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"finished_good_batch_id" uuid,
	"product_sku_id" uuid,
	"reserved_qty" numeric(18, 4),
	"channel" varchar(30),
	"reserved_for_document_id" uuid,
	"reserved_dt" timestamp with time zone,
	"released_dt" timestamp with time zone,
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "product_sku_id" uuid;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "reserved_qty" numeric(18, 4);
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "channel" varchar(30);
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "reserved_for_document_id" uuid;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "reserved_dt" timestamp with time zone;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "released_dt" timestamp with time zone;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."finished_good_reservation" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."finished_goods_batch_consumption" (
	"finished_goods_batch_consumption_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"finished_good_batch_id" uuid,
	"consumed_for_document_id" uuid,
	"consumed_qty" numeric(18, 4),
	"uom_id" uuid,
	"consumed_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_for_document_id" uuid;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_qty" numeric(18, 4);
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "consumed_dt" timestamp with time zone;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "packaging"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "packaging"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "packaging"."package_order" (
	"package_order_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"product_sku_id" uuid,
	"oil_batch_id" uuid,
	"location_id" uuid,
	"order_qty" numeric(18, 4),
	"uom_id" uuid,
	"planned_start_dt" timestamp with time zone,
	"planned_end_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "product_sku_id" uuid;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "oil_batch_id" uuid;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "location_id" uuid;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "order_qty" numeric(18, 4);
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "planned_start_dt" timestamp with time zone;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "planned_end_dt" timestamp with time zone;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."package_order" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."package_order_item" (
	"package_order_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"package_order_id" uuid,
	"packaging_material_id" uuid,
	"required_qty" numeric(18, 4),
	"issued_qty" boolean,
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "package_order_id" uuid;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "packaging_material_id" uuid;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "issued_qty" boolean;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."package_order_item" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."packaging_bom_master" (
	"packaging_bom_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"product_sku_id" uuid,
	"packaging_material_id" uuid,
	"required_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "product_sku_id" uuid;
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "packaging_material_id" uuid;
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "required_qty" numeric(18, 4);
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."packaging_bom_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."packaging_material_master" (
	"packaging_material_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"packaging_material_code" varchar(50),
	"packaging_material_name" varchar(200),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "packaging_material_code" varchar(50);
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "packaging_material_name" varchar(200);
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."packaging_material_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."packaging_qc" (
	"packaging_qc_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"finished_good_batch_id" uuid,
	"leakage_check" varchar(30),
	"label_check" varchar(30),
	"carton_check" varchar(30),
	"overall_result" varchar(30),
	"inspected_by" uuid,
	"inspection_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "leakage_check" varchar(30);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "label_check" varchar(30);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "carton_check" varchar(30);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "overall_result" varchar(30);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "inspected_by" uuid;
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "inspection_dt" timestamp with time zone;
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."packaging_qc" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."product_category_master" (
	"product_category_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"category_code" varchar(50),
	"category_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "category_code" varchar(50);
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "category_name" varchar(200);
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."product_category_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."product_master" (
	"product_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"brand_id" uuid,
	"product_category_id" uuid,
	"product_code" varchar(50),
	"product_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "brand_id" uuid;
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "product_category_id" uuid;
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "product_code" varchar(50);
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "product_name" varchar(200);
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."product_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "packaging"."product_sku" (
	"product_sku_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"product_id" uuid,
	"sku_code" varchar(50),
	"pack_size" varchar(255),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "product_id" uuid;
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "sku_code" varchar(50);
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "pack_size" varchar(255);
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "packaging"."product_sku" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "packaging"."filling_session_details" ADD CONSTRAINT "filling_session_details_filling_session_id_filling_session_filling_session_id_fk" FOREIGN KEY ("filling_session_id") REFERENCES "packaging"."filling_session"("filling_session_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."finished_good_reservation" ADD CONSTRAINT "finished_good_reservation_finished_good_batch_id_finished_good_batch_master_finished_good_batch_id_fk" FOREIGN KEY ("finished_good_batch_id") REFERENCES "packaging"."finished_good_batch_master"("finished_good_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."finished_goods_batch_consumption" ADD CONSTRAINT "finished_goods_batch_consumption_finished_good_batch_id_finished_good_batch_master_finished_good_batch_id_fk" FOREIGN KEY ("finished_good_batch_id") REFERENCES "packaging"."finished_good_batch_master"("finished_good_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."package_order_item" ADD CONSTRAINT "package_order_item_package_order_id_package_order_package_order_id_fk" FOREIGN KEY ("package_order_id") REFERENCES "packaging"."package_order"("package_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."packaging_qc" ADD CONSTRAINT "packaging_qc_finished_good_batch_id_finished_good_batch_master_finished_good_batch_id_fk" FOREIGN KEY ("finished_good_batch_id") REFERENCES "packaging"."finished_good_batch_master"("finished_good_batch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."product_master" ADD CONSTRAINT "product_master_product_category_id_product_category_master_product_category_id_fk" FOREIGN KEY ("product_category_id") REFERENCES "packaging"."product_category_master"("product_category_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "packaging"."product_sku" ADD CONSTRAINT "product_sku_product_id_product_master_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "packaging"."product_master"("product_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "packaging"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "packaging"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "packaging"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "packaging"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "packaging"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "filling_session_order_idx" ON "packaging"."filling_session" USING btree ("package_order_id");
CREATE INDEX IF NOT EXISTS "filling_session_details_session_idx" ON "packaging"."filling_session_details" USING btree ("filling_session_id");
CREATE INDEX IF NOT EXISTS "finished_good_batch_master_order_idx" ON "packaging"."finished_good_batch_master" USING btree ("package_order_id");
CREATE INDEX IF NOT EXISTS "finished_good_batch_master_sku_idx" ON "packaging"."finished_good_batch_master" USING btree ("product_sku_id");
CREATE INDEX IF NOT EXISTS "finished_good_reservation_batch_idx" ON "packaging"."finished_good_reservation" USING btree ("finished_good_batch_id");
CREATE INDEX IF NOT EXISTS "finished_good_reservation_sku_idx" ON "packaging"."finished_good_reservation" USING btree ("product_sku_id");
CREATE INDEX IF NOT EXISTS "finished_good_reservation_document_idx" ON "packaging"."finished_good_reservation" USING btree ("reserved_for_document_id");
CREATE INDEX IF NOT EXISTS "finished_goods_batch_consumption_batch_idx" ON "packaging"."finished_goods_batch_consumption" USING btree ("finished_good_batch_id");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "packaging"."outbox" USING btree ("occurred_at","seq") WHERE "packaging"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "packaging"."outbox" USING btree ("aggregate_id");
CREATE INDEX IF NOT EXISTS "package_order_sku_idx" ON "packaging"."package_order" USING btree ("product_sku_id");
CREATE INDEX IF NOT EXISTS "package_order_oil_batch_idx" ON "packaging"."package_order" USING btree ("oil_batch_id");
CREATE INDEX IF NOT EXISTS "package_order_location_idx" ON "packaging"."package_order" USING btree ("location_id");
CREATE INDEX IF NOT EXISTS "package_order_item_order_idx" ON "packaging"."package_order_item" USING btree ("package_order_id");
CREATE INDEX IF NOT EXISTS "package_order_item_material_idx" ON "packaging"."package_order_item" USING btree ("packaging_material_id");
CREATE INDEX IF NOT EXISTS "packaging_bom_master_sku_idx" ON "packaging"."packaging_bom_master" USING btree ("product_sku_id");
CREATE INDEX IF NOT EXISTS "packaging_bom_master_material_idx" ON "packaging"."packaging_bom_master" USING btree ("packaging_material_id");
CREATE UNIQUE INDEX IF NOT EXISTS "packaging_material_master_code_uq" ON "packaging"."packaging_material_master" USING btree ("packaging_material_code");
CREATE INDEX IF NOT EXISTS "packaging_qc_batch_idx" ON "packaging"."packaging_qc" USING btree ("finished_good_batch_id");
CREATE UNIQUE INDEX IF NOT EXISTS "product_category_master_code_uq" ON "packaging"."product_category_master" USING btree ("category_code");
CREATE UNIQUE INDEX IF NOT EXISTS "product_master_code_uq" ON "packaging"."product_master" USING btree ("product_code");
CREATE INDEX IF NOT EXISTS "product_master_category_idx" ON "packaging"."product_master" USING btree ("product_category_id");
CREATE INDEX IF NOT EXISTS "product_master_formula_idx" ON "packaging"."product_master" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "product_master_brand_idx" ON "packaging"."product_master" USING btree ("brand_id");
CREATE UNIQUE INDEX IF NOT EXISTS "product_sku_code_uq" ON "packaging"."product_sku" USING btree ("sku_code");
CREATE INDEX IF NOT EXISTS "product_sku_product_idx" ON "packaging"."product_sku" USING btree ("product_id");
