-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-sales.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "sales";

CREATE TABLE IF NOT EXISTS "sales"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "sales"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "sales"."customer_master" (
	"customer_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"customer_code" varchar(50),
	"customer_name" varchar(200),
	"address_id" uuid,
	"base_currency_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "customer_code" varchar(50);
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "customer_name" varchar(200);
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "address_id" uuid;
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "base_currency_id" uuid;
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."customer_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "sales"."dispatch_items" (
	"dispatch_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"dispatch_id" uuid,
	"sales_order_item_id" uuid,
	"finished_good_batch_id" uuid,
	"dispatched_qty" numeric(18, 4),
	"uom_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "dispatch_id" uuid;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "sales_order_item_id" uuid;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "finished_good_batch_id" uuid;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "dispatched_qty" numeric(18, 4);
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."dispatch_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "sales"."dispatch_master" (
	"dispatch_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"sales_order_id" uuid,
	"customer_id" uuid,
	"dispatch_date" date,
	"vehicle_number" varchar(20),
	"transporter_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "sales_order_id" uuid;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "customer_id" uuid;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "dispatch_date" date;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "vehicle_number" varchar(20);
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "transporter_id" uuid;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."dispatch_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "sales"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "sales"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "sales"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "sales"."sales_order" (
	"sales_order_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"so_number" varchar(50),
	"customer_id" uuid,
	"order_date" date,
	"delivery_location_id" uuid,
	"currency_id" uuid,
	"total_amount" numeric(18, 4),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "so_number" varchar(50);
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "customer_id" uuid;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "order_date" date;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "delivery_location_id" uuid;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "currency_id" uuid;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "total_amount" numeric(18, 4);
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."sales_order" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "sales"."sales_order_items" (
	"sales_order_item_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"sales_order_id" uuid,
	"product_sku_id" uuid,
	"ordered_qty" numeric(18, 4),
	"uom_id" uuid,
	"rate" numeric(18, 4),
	"amount" numeric(18, 4),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "sales_order_id" uuid;
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "product_sku_id" uuid;
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "ordered_qty" numeric(18, 4);
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "uom_id" uuid;
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "rate" numeric(18, 4);
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "amount" numeric(18, 4);
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."sales_order_items" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "sales"."transporter_master" (
	"transporter_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"transporter_code" varchar(50),
	"transporter_name" varchar(200),
	"contact_id" uuid,
	"address_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "transporter_code" varchar(50);
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "transporter_name" varchar(200);
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "contact_id" uuid;
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "address_id" uuid;
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "sales"."transporter_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
DO $$ BEGIN
  ALTER TABLE "sales"."dispatch_items" ADD CONSTRAINT "dispatch_items_dispatch_id_dispatch_master_dispatch_id_fk" FOREIGN KEY ("dispatch_id") REFERENCES "sales"."dispatch_master"("dispatch_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "sales"."sales_order_items" ADD CONSTRAINT "sales_order_items_sales_order_id_sales_order_sales_order_id_fk" FOREIGN KEY ("sales_order_id") REFERENCES "sales"."sales_order"("sales_order_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "sales"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "sales"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "sales"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "sales"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "sales"."audit_events" USING btree ("chain_seq");
CREATE UNIQUE INDEX IF NOT EXISTS "customer_master_code_uq" ON "sales"."customer_master" USING btree ("customer_code");
CREATE INDEX IF NOT EXISTS "dispatch_items_dispatch_idx" ON "sales"."dispatch_items" USING btree ("dispatch_id");
CREATE INDEX IF NOT EXISTS "dispatch_items_sales_order_item_idx" ON "sales"."dispatch_items" USING btree ("sales_order_item_id");
CREATE INDEX IF NOT EXISTS "dispatch_items_fg_batch_idx" ON "sales"."dispatch_items" USING btree ("finished_good_batch_id");
CREATE INDEX IF NOT EXISTS "dispatch_master_customer_idx" ON "sales"."dispatch_master" USING btree ("customer_id");
CREATE INDEX IF NOT EXISTS "dispatch_master_sales_order_idx" ON "sales"."dispatch_master" USING btree ("sales_order_id");
CREATE INDEX IF NOT EXISTS "dispatch_master_transporter_idx" ON "sales"."dispatch_master" USING btree ("transporter_id");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "sales"."outbox" USING btree ("occurred_at","seq") WHERE "sales"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "sales"."outbox" USING btree ("aggregate_id");
CREATE UNIQUE INDEX IF NOT EXISTS "sales_order_so_number_uq" ON "sales"."sales_order" USING btree ("so_number");
CREATE INDEX IF NOT EXISTS "sales_order_customer_idx" ON "sales"."sales_order" USING btree ("customer_id");
CREATE INDEX IF NOT EXISTS "sales_order_items_order_idx" ON "sales"."sales_order_items" USING btree ("sales_order_id");
CREATE INDEX IF NOT EXISTS "sales_order_items_sku_idx" ON "sales"."sales_order_items" USING btree ("product_sku_id");
CREATE UNIQUE INDEX IF NOT EXISTS "transporter_master_code_uq" ON "sales"."transporter_master" USING btree ("transporter_code");
