-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-workflow-state.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "workflow";

CREATE TABLE IF NOT EXISTS "workflow"."workflow_state_master" (
	"workflow_state_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workflow_name" varchar(200),
	"state_code" varchar(50),
	"state_name" varchar(200),
	"is_initial" boolean DEFAULT false NOT NULL,
	"is_final" boolean DEFAULT false NOT NULL,
	"sort_order" integer,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "workflow_name" varchar(200);
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "state_code" varchar(50);
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "state_name" varchar(200);
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "is_initial" boolean DEFAULT false NOT NULL;
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "is_final" boolean DEFAULT false NOT NULL;
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "sort_order" integer;
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "workflow"."workflow_state_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "workflow"."workflow_transaction_master" (
	"workflow_transaction_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"workflow_name" varchar(200),
	"entity_type" varchar(100),
	"entity_id" uuid,
	"from_state_id" uuid,
	"to_state_id" uuid,
	"transition_action" varchar(100),
	"performed_by" uuid,
	"transaction_dt" timestamp with time zone,
	"comments" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "workflow_name" varchar(200);
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "entity_type" varchar(100);
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "from_state_id" uuid;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "to_state_id" uuid;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "transition_action" varchar(100);
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "performed_by" uuid;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "transaction_dt" timestamp with time zone;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "comments" text;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "workflow"."workflow_transaction_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE INDEX IF NOT EXISTS "workflow_state_master_name_idx" ON "workflow"."workflow_state_master" USING btree ("workflow_name");
CREATE INDEX IF NOT EXISTS "workflow_transaction_master_entity_idx" ON "workflow"."workflow_transaction_master" USING btree ("entity_id");
CREATE INDEX IF NOT EXISTS "workflow_transaction_master_from_state_idx" ON "workflow"."workflow_transaction_master" USING btree ("from_state_id");
CREATE INDEX IF NOT EXISTS "workflow_transaction_master_to_state_idx" ON "workflow"."workflow_transaction_master" USING btree ("to_state_id");
CREATE INDEX IF NOT EXISTS "workflow_transaction_master_performed_by_idx" ON "workflow"."workflow_transaction_master" USING btree ("performed_by");
