-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-bridge.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: main

CREATE SCHEMA IF NOT EXISTS "bridge";

CREATE TABLE IF NOT EXISTS "bridge"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "bridge"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "bridge"."connector_config" (
	"id" varchar(50) PRIMARY KEY DEFAULT 'default' NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"webhook_url" text,
	"hmac_secret_sealed" text,
	"configured_at" timestamp with time zone,
	"configured_by" varchar(255)
);

ALTER TABLE "bridge"."connector_config" ADD COLUMN IF NOT EXISTS "enabled" boolean DEFAULT false NOT NULL;
ALTER TABLE "bridge"."connector_config" ADD COLUMN IF NOT EXISTS "webhook_url" text;
ALTER TABLE "bridge"."connector_config" ADD COLUMN IF NOT EXISTS "hmac_secret_sealed" text;
ALTER TABLE "bridge"."connector_config" ADD COLUMN IF NOT EXISTS "configured_at" timestamp with time zone;
ALTER TABLE "bridge"."connector_config" ADD COLUMN IF NOT EXISTS "configured_by" varchar(255);
CREATE TABLE IF NOT EXISTS "bridge"."facts_nonce" (
	"nonce" varchar(255) PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "bridge"."facts_nonce" ADD COLUMN IF NOT EXISTS "expires_at" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."facts_nonce" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
CREATE TABLE IF NOT EXISTS "bridge"."inbound_event" (
	"event_id" uuid PRIMARY KEY NOT NULL,
	"version" integer NOT NULL,
	"type" text NOT NULL,
	"aggregate_id" uuid NOT NULL,
	"correlation_id" uuid NOT NULL,
	"causation_id" uuid,
	"occurred_at" timestamp with time zone NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"payload" jsonb NOT NULL,
	"processed_at" timestamp with time zone,
	"parked_reason" text
);

ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "version" integer;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "correlation_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "causation_id" uuid;
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "received_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "processed_at" timestamp with time zone;
ALTER TABLE "bridge"."inbound_event" ADD COLUMN IF NOT EXISTS "parked_reason" text;
CREATE TABLE IF NOT EXISTS "bridge"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "bridge"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "bridge"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
CREATE TABLE IF NOT EXISTS "bridge"."production_requirement" (
	"production_requirement_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"alembic_requirement_id" uuid NOT NULL,
	"org_id" uuid NOT NULL,
	"correlation_id" uuid NOT NULL,
	"order_ref" varchar(100) NOT NULL,
	"mapped_sku" text NOT NULL,
	"qty" numeric NOT NULL,
	"uom" varchar(20) NOT NULL,
	"pack_size" varchar(50),
	"needed_by" timestamp with time zone NOT NULL,
	"priority" varchar(20) DEFAULT 'normal' NOT NULL,
	"lifecycle_status" varchar(30) DEFAULT 'CREATED' NOT NULL,
	"status_reason" text,
	"production_order_id" uuid,
	"last_applied_version" numeric DEFAULT '0' NOT NULL,
	"last_emitted_version" numeric DEFAULT '0' NOT NULL,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "alembic_requirement_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "org_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "correlation_id" uuid;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "order_ref" varchar(100);  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "mapped_sku" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "qty" numeric;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "uom" varchar(20);  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "pack_size" varchar(50);
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "needed_by" timestamp with time zone;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "priority" varchar(20) DEFAULT 'normal' NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "lifecycle_status" varchar(30) DEFAULT 'CREATED' NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "status_reason" text;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "production_order_id" uuid;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "last_applied_version" numeric DEFAULT '0' NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "last_emitted_version" numeric DEFAULT '0' NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "bridge"."production_requirement" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "bridge"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "bridge"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "bridge"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "bridge"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "bridge"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "bridge_inbound_event_unprocessed_idx" ON "bridge"."inbound_event" USING btree ("received_at");
CREATE INDEX IF NOT EXISTS "bridge_inbound_event_aggregate_idx" ON "bridge"."inbound_event" USING btree ("aggregate_id","version");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "bridge"."outbox" USING btree ("occurred_at","seq") WHERE "bridge"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "bridge"."outbox" USING btree ("aggregate_id");
CREATE UNIQUE INDEX IF NOT EXISTS "bridge_production_requirement_alembic_id_uq" ON "bridge"."production_requirement" USING btree ("alembic_requirement_id");
CREATE INDEX IF NOT EXISTS "bridge_production_requirement_status_idx" ON "bridge"."production_requirement" USING btree ("lifecycle_status");
CREATE INDEX IF NOT EXISTS "bridge_production_requirement_order_idx" ON "bridge"."production_requirement" USING btree ("order_ref");
