-- GENERATED by scripts/gen-schema-migrations.mjs from the Drizzle table definitions
-- in @ra/data-formula.
-- Do not hand-edit: change the Drizzle schema and re-run the generator.
-- @target: formula

CREATE SCHEMA IF NOT EXISTS "formula";

CREATE TABLE IF NOT EXISTS "formula"."audit_events" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" uuid,
	"before" jsonb,
	"after" jsonb,
	"request_id" text,
	"ip" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"chain_seq" bigint,
	"prev_hash" text,
	"row_hash" text
);

ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "actor_id" uuid;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "action" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "entity_type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "entity_id" uuid;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "before" jsonb;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "after" jsonb;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "request_id" text;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "ip" text;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "chain_seq" bigint;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "prev_hash" text;
ALTER TABLE "formula"."audit_events" ADD COLUMN IF NOT EXISTS "row_hash" text;
CREATE TABLE IF NOT EXISTS "formula"."formula_access_policy" (
	"formula_access_policy_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"role_id" uuid,
	"user_id" uuid,
	"access_level" integer,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "role_id" uuid;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "user_id" uuid;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "access_level" integer;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_access_policy" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_approval" (
	"formula_approval_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_version_id" uuid,
	"approver_user_id" uuid,
	"approval_level" integer,
	"approval_status" varchar(30),
	"approved_dt" timestamp with time zone,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "approver_user_id" uuid;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "approval_level" integer;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "approval_status" varchar(30);
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_approval" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_change_log" (
	"formula_change_log_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"formula_version_id" uuid,
	"field_name" varchar(200),
	"old_value" text,
	"new_value" text,
	"change_reason" text,
	"changed_by" uuid,
	"changed_dt" timestamp with time zone,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "field_name" varchar(200);
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "old_value" text;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "new_value" text;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "change_reason" text;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "changed_by" uuid;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "changed_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_change_log" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_copy_request" (
	"formula_copy_request_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"source_formula_id" uuid,
	"source_version_id" uuid,
	"target_formula_id" uuid,
	"requested_by" uuid,
	"requested_dt" timestamp with time zone,
	"approved_by" uuid,
	"approved_dt" timestamp with time zone,
	"copy_notes" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "source_formula_id" uuid;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "source_version_id" uuid;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "target_formula_id" uuid;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "requested_by" uuid;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "requested_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "approved_by" uuid;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "copy_notes" text;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_copy_request" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_document_mapping" (
	"formula_document_mapping_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"formula_version_id" uuid,
	"document_type_id" uuid,
	"document_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "document_type_id" uuid;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "document_id" uuid;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_document_mapping" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_event_hist" (
	"formula_event_hist_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"formula_version_id" uuid,
	"event_type" varchar(50),
	"event_dt" timestamp with time zone,
	"performed_by" uuid,
	"remarks" text,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "event_type" varchar(50);
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "event_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "performed_by" uuid;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "remarks" text;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_event_hist" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_ingredients" (
	"formula_ingredients_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_version_id" uuid,
	"enc_payload" text NOT NULL,
	"enc_iv" text NOT NULL,
	"enc_tag" text NOT NULL,
	"sequence_no" integer,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "enc_payload" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "enc_iv" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "enc_tag" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "sequence_no" integer;
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_ingredients" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_master" (
	"formula_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_type_id" uuid,
	"formula_code" varchar(50),
	"formula_name" varchar(200),
	"formula_owner_user_id" uuid,
	"current_version_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "formula_type_id" uuid;
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "formula_code" varchar(50);
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "formula_name" varchar(200);
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "formula_owner_user_id" uuid;
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "current_version_id" uuid;
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_stage_ingredients" (
	"formula_stage_ingredients_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_stage_id" uuid,
	"enc_payload" text NOT NULL,
	"enc_iv" text NOT NULL,
	"enc_tag" text NOT NULL,
	"sequence_no" integer,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "formula_stage_id" uuid;
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "enc_payload" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "enc_iv" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "enc_tag" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "sequence_no" integer;
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_stage_ingredients" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_stage_master" (
	"formula_stage_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_version_id" uuid,
	"stage_name" varchar(200),
	"sequence_no" integer,
	"stage_instructions" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "formula_version_id" uuid;
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "stage_name" varchar(200);
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "sequence_no" integer;
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "stage_instructions" varchar(255);
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_stage_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_type_master" (
	"formula_type_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type_code" varchar(50),
	"type_name" varchar(200),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "type_code" varchar(50);
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "type_name" varchar(200);
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_type_master" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_vault" (
	"formula_vault_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"encryption_key_ref" varchar(255),
	"vault_location" varchar(255),
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "encryption_key_ref" varchar(255);
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "vault_location" varchar(255);
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_vault" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."formula_version" (
	"formula_version_id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"formula_id" uuid,
	"version_number" integer,
	"approved_by" uuid,
	"approved_dt" timestamp with time zone,
	"submitted_by" uuid,
	"submitted_dt" timestamp with time zone,
	"locked_by" uuid,
	"locked_dt" timestamp with time zone,
	"superseded_by_version_id" uuid,
	"status" varchar(30),
	"created_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_dt" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(255),
	"updated_by" varchar(255)
);

ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "formula_id" uuid;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "version_number" integer;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "approved_by" uuid;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "approved_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "submitted_by" uuid;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "submitted_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "locked_by" uuid;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "locked_dt" timestamp with time zone;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "superseded_by_version_id" uuid;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "status" varchar(30);
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "created_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "updated_dt" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "created_by" varchar(255);
ALTER TABLE "formula"."formula_version" ADD COLUMN IF NOT EXISTS "updated_by" varchar(255);
CREATE TABLE IF NOT EXISTS "formula"."outbox" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"aggregate_id" uuid,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "formula"."outbox_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1)
);

ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "type" text;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "payload" jsonb;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "aggregate_id" uuid;
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "occurred_at" timestamp with time zone DEFAULT now() NOT NULL;
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "published_at" timestamp with time zone;
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "attempts" integer DEFAULT 0 NOT NULL;
ALTER TABLE "formula"."outbox" ADD COLUMN IF NOT EXISTS "seq" bigint;  -- relaxed from NOT NULL: no default to backfill existing rows with safely
DO $$ BEGIN
  ALTER TABLE "formula"."formula_access_policy" ADD CONSTRAINT "formula_access_policy_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_approval" ADD CONSTRAINT "formula_approval_formula_version_id_formula_version_formula_version_id_fk" FOREIGN KEY ("formula_version_id") REFERENCES "formula"."formula_version"("formula_version_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_change_log" ADD CONSTRAINT "formula_change_log_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_document_mapping" ADD CONSTRAINT "formula_document_mapping_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_event_hist" ADD CONSTRAINT "formula_event_hist_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_ingredients" ADD CONSTRAINT "formula_ingredients_formula_version_id_formula_version_formula_version_id_fk" FOREIGN KEY ("formula_version_id") REFERENCES "formula"."formula_version"("formula_version_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_master" ADD CONSTRAINT "formula_master_formula_type_id_formula_type_master_formula_type_id_fk" FOREIGN KEY ("formula_type_id") REFERENCES "formula"."formula_type_master"("formula_type_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_stage_ingredients" ADD CONSTRAINT "formula_stage_ingredients_formula_stage_id_formula_stage_master_formula_stage_id_fk" FOREIGN KEY ("formula_stage_id") REFERENCES "formula"."formula_stage_master"("formula_stage_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_stage_master" ADD CONSTRAINT "formula_stage_master_formula_version_id_formula_version_formula_version_id_fk" FOREIGN KEY ("formula_version_id") REFERENCES "formula"."formula_version"("formula_version_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_vault" ADD CONSTRAINT "formula_vault_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "formula"."formula_version" ADD CONSTRAINT "formula_version_formula_id_formula_master_formula_id_fk" FOREIGN KEY ("formula_id") REFERENCES "formula"."formula_master"("formula_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS "audit_events_entity_idx" ON "formula"."audit_events" USING btree ("entity_type","entity_id");
CREATE INDEX IF NOT EXISTS "audit_events_actor_idx" ON "formula"."audit_events" USING btree ("actor_id");
CREATE INDEX IF NOT EXISTS "audit_events_occurred_idx" ON "formula"."audit_events" USING btree ("occurred_at");
CREATE INDEX IF NOT EXISTS "audit_events_request_idx" ON "formula"."audit_events" USING btree ("request_id");
CREATE INDEX IF NOT EXISTS "audit_events_chain_seq_idx" ON "formula"."audit_events" USING btree ("chain_seq");
CREATE INDEX IF NOT EXISTS "formula_access_policy_formula_idx" ON "formula"."formula_access_policy" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_access_policy_role_idx" ON "formula"."formula_access_policy" USING btree ("role_id");
CREATE INDEX IF NOT EXISTS "formula_access_policy_user_idx" ON "formula"."formula_access_policy" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "formula_approval_version_idx" ON "formula"."formula_approval" USING btree ("formula_version_id");
CREATE INDEX IF NOT EXISTS "formula_approval_approver_idx" ON "formula"."formula_approval" USING btree ("approver_user_id");
CREATE INDEX IF NOT EXISTS "formula_change_log_formula_idx" ON "formula"."formula_change_log" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_change_log_version_idx" ON "formula"."formula_change_log" USING btree ("formula_version_id");
CREATE INDEX IF NOT EXISTS "formula_copy_request_source_idx" ON "formula"."formula_copy_request" USING btree ("source_formula_id");
CREATE INDEX IF NOT EXISTS "formula_copy_request_target_idx" ON "formula"."formula_copy_request" USING btree ("target_formula_id");
CREATE INDEX IF NOT EXISTS "formula_document_mapping_formula_idx" ON "formula"."formula_document_mapping" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_document_mapping_version_idx" ON "formula"."formula_document_mapping" USING btree ("formula_version_id");
CREATE INDEX IF NOT EXISTS "formula_event_hist_formula_idx" ON "formula"."formula_event_hist" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_event_hist_version_idx" ON "formula"."formula_event_hist" USING btree ("formula_version_id");
CREATE INDEX IF NOT EXISTS "formula_ingredients_version_idx" ON "formula"."formula_ingredients" USING btree ("formula_version_id");
CREATE UNIQUE INDEX IF NOT EXISTS "formula_master_code_uq" ON "formula"."formula_master" USING btree ("formula_code");
CREATE INDEX IF NOT EXISTS "formula_master_type_idx" ON "formula"."formula_master" USING btree ("formula_type_id");
CREATE INDEX IF NOT EXISTS "formula_master_owner_idx" ON "formula"."formula_master" USING btree ("formula_owner_user_id");
CREATE INDEX IF NOT EXISTS "formula_master_current_version_idx" ON "formula"."formula_master" USING btree ("current_version_id");
CREATE INDEX IF NOT EXISTS "formula_stage_ingredients_stage_idx" ON "formula"."formula_stage_ingredients" USING btree ("formula_stage_id");
CREATE INDEX IF NOT EXISTS "formula_stage_master_version_idx" ON "formula"."formula_stage_master" USING btree ("formula_version_id");
CREATE UNIQUE INDEX IF NOT EXISTS "formula_type_master_code_uq" ON "formula"."formula_type_master" USING btree ("type_code");
CREATE INDEX IF NOT EXISTS "formula_vault_formula_idx" ON "formula"."formula_vault" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_version_formula_idx" ON "formula"."formula_version" USING btree ("formula_id");
CREATE INDEX IF NOT EXISTS "formula_version_approved_by_idx" ON "formula"."formula_version" USING btree ("approved_by");
CREATE INDEX IF NOT EXISTS "formula_version_superseded_by_idx" ON "formula"."formula_version" USING btree ("superseded_by_version_id");
CREATE INDEX IF NOT EXISTS "outbox_unpublished_idx" ON "formula"."outbox" USING btree ("occurred_at","seq") WHERE "formula"."outbox"."published_at" IS NULL;
CREATE INDEX IF NOT EXISTS "outbox_aggregate_idx" ON "formula"."outbox" USING btree ("aggregate_id");
