// Prints, as one JSON object on stdout, every fact ALEMBIC's
// ops/scripts/access-catalog.mjs (PB-05/SB-03/PB-13, V4 §102-§104/§112-§114)
// needs from this repository's own role/permission source of truth
// (scripts/ra-roles.ts + scripts/ra-permissions.ts) to build the shared
// release/access/*.json catalogs.
//
// WHY A SEPARATE SCRIPT RATHER THAN ALEMBIC IMPORTING ra-roles.ts DIRECTLY.
// `RoleDef.select` is a PREDICATE FUNCTION (`(permissionCode) => boolean`),
// the same shape scripts/db-seed.ts already runs to build role_permission_
// mapping rows. A static reader of the source text cannot evaluate an
// arbitrary predicate without re-implementing it, and re-implementing it is
// exactly the kind of second copy that drifts from the one the seed actually
// runs. Executing it here, in THIS repository, with THIS repository's own
// tsx, is the only way the computed permission set is guaranteed to be the
// same one scripts/db-seed.ts grants for real.
//
// ALEMBIC's ops/scripts/access-catalog.mjs runs this via
// `pnpm exec tsx scripts/access-catalog-export.ts` in $RAWPROD_DIR and reads
// stdout. When RAWPROD_DIR is unset (ALEMBIC CI does not check RawProd out),
// the generator falls back to the snapshot this script's own output was used
// to write: release/access/.rawprod-snapshot.json, committed in ALEMBIC.
//
//   npx tsx scripts/access-catalog-export.ts
//
// ROUTE-ACCESS INVENTORY (Lane GUARD, security review -- PermissionsGuard
// used to fail OPEN on any undecorated route). ALEMBIC's PB-05/§112
// UNMAPPED_MUTATING_API_ROUTES/UNMAPPED_READ_API_ROUTES scan used to carry
// its OWN hand-maintained exemption table naming the handful of RawProd
// routes that don't have a static @Permissions decorator (dynamic
// per-:resource checks, self-service actions). That table could drift from
// the real source the same way a re-implemented role predicate could -- a
// route renamed or removed on the RawProd side left a stale entry behind,
// and a NEW undecorated route added on the RawProd side had no entry at
// all, silently reappearing in ALEMBIC's UNMAPPED_* lists (or worse, not).
// `routeAccess` below replaces that hand-maintained table: it's generated by
// statically walking every backend/**/*.controller.ts in THIS checkout and
// reading off the real `@Permissions`/`@Public`/`@SelfService`/
// `@DynamicPermission`/`@AnyAuthenticated` decorators (see
// backend-kernel/src/decorators/*.ts + edge/permissions.guard.ts, and
// backend/api/src/__tests__/route-inventory.test.ts, which fails RawProd's
// own test suite if any route has none of them) -- so ALEMBIC reads
// ALEMBIC's exemptions from RawProd's actual source instead of a copy of it.
import { readdirSync, statSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import ts from 'typescript';
import {
  ROLES,
  VAULT_PLAINTEXT_PERMISSION,
  VAULT_PLAINTEXT_ROLES,
  PLATFORM_OPS_PERMISSION,
  PLATFORM_OPS_ROLES,
  ROLE_GRANT_PERMISSION,
  ROLE_GRANTERS,
  FORMULA_DECISION_PERMISSIONS,
  FORMULATOR_FORBIDDEN_PERMISSIONS,
  VAULT_APPROVER_FORBIDDEN_PERMISSIONS,
  MANUFACTURING_INSTRUCTION_PERMISSION,
  MANUFACTURING_INSTRUCTION_ROLES,
  CAPABILITY_PERMISSIONS,
} from './ra-roles.js';
import { RA_PERMISSIONS } from './ra-permissions.js';
// G4 (lane F3, tutorial engine): imports the ACTUAL lesson objects the tutorial runner and the
// backend registry both read (backend/api/src/tutorial/tutorial-lessons.ts) — never a hand-
// duplicated copy, so this export can't drift from what the app really offers. See that file's
// own header for why it has zero NestJS/DB dependencies and is safe to import from a plain
// Node script like this one.
import { TUTORIAL_LESSONS, lessonPermissions } from '../backend/api/src/tutorial/tutorial-lessons.js';

const ALL_PERMISSIONS = [...RA_PERMISSIONS, ...CAPABILITY_PERMISSIONS];

/* ── route-access inventory (static source scan, no NestJS runtime needed) ── */

const HTTP_DECORATORS = new Set(['Get', 'Post', 'Put', 'Patch', 'Delete', 'Head', 'Options', 'All']);
const MARKER_DECORATORS = new Set([
  'Public',
  'Permissions',
  'SelfService',
  'DynamicPermission',
  'AnyAuthenticated',
]);

interface RouteAccessEntry {
  file: string;
  controller: string;
  method: string;
  httpMethods: string[];
  path: string | null;
  decision: 'public' | 'permissions' | 'self-service' | 'dynamic-permission' | 'any-authenticated' | 'none';
  permissions?: string[];
  reason?: string;
}

function walkControllerFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === 'node_modules' || entry === 'dist') continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walkControllerFiles(full, out);
    else if (entry.endsWith('.controller.ts')) out.push(full);
  }
  return out;
}

function decoratorName(expr: ts.LeftHandSideExpression): string | null {
  if (ts.isCallExpression(expr)) return decoratorName(expr.expression);
  if (ts.isIdentifier(expr)) return expr.text;
  if (ts.isPropertyAccessExpression(expr)) return expr.name.text;
  return null;
}

function stringArg(expr: ts.LeftHandSideExpression, argIndex = 0): string | undefined {
  if (!ts.isCallExpression(expr)) return undefined;
  const arg = expr.arguments[argIndex];
  return arg && ts.isStringLiteral(arg) ? arg.text : undefined;
}

function allStringArgs(expr: ts.LeftHandSideExpression): string[] {
  if (!ts.isCallExpression(expr)) return [];
  return expr.arguments.filter(ts.isStringLiteral).map((a) => a.text);
}

function buildRouteAccessInventory(repoRoot: string): RouteAccessEntry[] {
  const controllerFiles = walkControllerFiles(join(repoRoot, 'backend')).sort();
  const entries: RouteAccessEntry[] = [];

  for (const file of controllerFiles) {
    const src = readFileSync(file, 'utf8');
    const sourceFile = ts.createSourceFile(file, src, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);

    ts.forEachChild(sourceFile, function visit(node) {
      if (ts.isClassDeclaration(node) && node.name) {
        for (const member of node.members) {
          if (!ts.isMethodDeclaration(member) || !ts.canHaveDecorators(member)) continue;
          const decorators = ts.getDecorators(member) ?? [];
          const named = decorators
            .map((d) => ({ name: decoratorName(d.expression), expr: d.expression }))
            .filter((d): d is { name: string; expr: ts.LeftHandSideExpression } => d.name !== null);

          const httpDecos = named.filter((d) => HTTP_DECORATORS.has(d.name));
          if (httpDecos.length === 0) continue; // not a route handler

          const path = httpDecos.map((d) => stringArg(d.expr)).find((p) => p !== undefined) ?? null;
          const marker = named.find((d) => MARKER_DECORATORS.has(d.name));

          let decision: RouteAccessEntry['decision'] = 'none';
          let permissions: string[] | undefined;
          let reason: string | undefined;
          switch (marker?.name) {
            case 'Public': decision = 'public'; break;
            case 'SelfService': decision = 'self-service'; break;
            case 'Permissions': decision = 'permissions'; permissions = allStringArgs(marker.expr); break;
            case 'DynamicPermission': decision = 'dynamic-permission'; reason = stringArg(marker.expr); break;
            case 'AnyAuthenticated': decision = 'any-authenticated'; reason = stringArg(marker.expr); break;
            default: decision = 'none';
          }

          entries.push({
            file: relative(repoRoot, file),
            controller: node.name.getText(sourceFile),
            method: member.name.getText(sourceFile),
            httpMethods: httpDecos.map((d) => d.name),
            path,
            decision,
            ...(permissions ? { permissions: permissions.sort() } : {}),
            ...(reason ? { reason } : {}),
          });
        }
      }
      ts.forEachChild(node, visit);
    });
  }

  return entries.sort((a, b) => `${a.controller}.${a.method}`.localeCompare(`${b.controller}.${b.method}`));
}

const routeAccess = buildRouteAccessInventory(process.cwd());

const roles = ROLES.map((role) => ({
  code: role.code,
  name: role.name,
  view: role.view,
  permissions: ALL_PERMISSIONS.filter((p) => role.select(p)).sort(),
}));

const out = {
  generatedAt: new Date().toISOString(),
  source: 'scripts/access-catalog-export.ts',
  permissions: [...RA_PERMISSIONS].sort(),
  capabilityPermissions: [...CAPABILITY_PERMISSIONS].sort(),
  roles,
  vaultPlaintextPermission: VAULT_PLAINTEXT_PERMISSION,
  vaultPlaintextRoles: [...VAULT_PLAINTEXT_ROLES].sort(),
  platformOpsPermission: PLATFORM_OPS_PERMISSION,
  platformOpsRoles: [...PLATFORM_OPS_ROLES].sort(),
  roleGrantPermission: ROLE_GRANT_PERMISSION,
  roleGranters: [...ROLE_GRANTERS].sort(),
  formulaDecisionPermissions: [...FORMULA_DECISION_PERMISSIONS].sort(),
  formulatorForbiddenPermissions: [...FORMULATOR_FORBIDDEN_PERMISSIONS].sort(),
  vaultApproverForbiddenPermissions: [...VAULT_APPROVER_FORBIDDEN_PERMISSIONS].sort(),
  manufacturingInstructionPermission: MANUFACTURING_INSTRUCTION_PERMISSION,
  manufacturingInstructionRoles: [...MANUFACTURING_INSTRUCTION_ROLES].sort(),
  // G4: one entry per in-app tutorial lesson, sourced from the SAME lesson objects the runner
  // renders (see the import above) — every action/verify step's permission is guaranteed to be
  // a live, current permission string (already asserted against RA_PERMISSIONS in
  // backend/api/src/tutorial/__tests__/tutorial-lessons.test.ts), which is what lets ALEMBIC
  // compute a UNMAPPED_TUTORIAL_FEATURES count of 0 for RawProd.
  tutorialLessons: TUTORIAL_LESSONS.map((lesson) => ({
    id: lesson.id,
    track: lesson.track,
    console: lesson.console,
    workspace: lesson.workspace,
    title: lesson.title,
    version: lesson.version,
    actions: lesson.steps
      .map((step) => ({ stepId: step.id, permission: 'permission' in step ? step.permission : undefined }))
      .filter((entry): entry is { stepId: string; permission: string } => Boolean(entry.permission)),
    allPermissions: lessonPermissions(lesson),
  })),
  // Replaces ALEMBIC's hand-maintained undecorated-route exemption table -- every controller
  // method with an HTTP decorator, its access decision, and (for the non-static decisions) the
  // verified reason string from the source. `decision: 'none'` should never appear here:
  // RawProd's own route-inventory.test.ts fails the build first if it would.
  routeAccess,
};

process.stdout.write(JSON.stringify(out));
